import type { FailureMode } from "./types";

const entries: FailureMode[] = [
  {
    id: "brief-event-blindness",
    index: 1,
    title: "The event between frames",
    shortTitle: "Brief-event blindness",
    subtitle:
      "A salient event can occur in the source video yet never enter the model’s effective observation stream.",
    modalities: ["video"],
    stages: ["frame-sampling", "compression"],
    capabilities: ["brief-event-detection", "state-transitions"],
    evidence: "behavioral-evidence",
    sourceIds: ["videoqa-study", "tempcompass", "video-mme-v2"],
    trigger: "Shorten a high-contrast event and vary its phase within an otherwise identical video.",
    symptom: "The model denies that the event occurred or answers according to adjacent sampled states.",
    violatedExpectation:
      "An event that remains easy for a human observer should influence the answer regardless of its phase in the file.",
    mechanism:
      "Consistent with frame subsampling or temporal pooling removing the event before downstream reasoning; native provider preprocessing is usually not disclosed.",
    alternatives: [
      "The event was sampled but poorly encoded",
      "The visual fact survived but language decoding ignored it",
      "Video transcoding altered the event",
    ],
    disconfirmingTest:
      "Provide the critical frame explicitly or lengthen only the event while keeping all semantic content fixed.",
    mitigations: [
      "Adaptive temporal sampling",
      "Motion-triggered glimpses",
      "Question-conditioned frame retrieval",
    ],
    severity: "foundational",
    reproducibility: "high",
    generator: "brief-event",
    accent: "vermillion",
    featured: true,
  },
  {
    id: "attribute-binding-swap",
    index: 2,
    title: "The right facts, on the wrong objects",
    shortTitle: "Attribute-binding swap",
    subtitle:
      "Models may detect every object and colour while assigning those attributes to the wrong entities.",
    modalities: ["image", "video"],
    stages: ["object-state-representation", "cross-modal-projection"],
    capabilities: ["attribute-binding", "comparison"],
    evidence: "literature-established",
    sourceIds: ["perceptionbench", "eyes-wide-shut"],
    trigger: "Present several similar objects with independently randomized colours, shapes, and positions.",
    symptom: "The response names attributes present in the image but binds them to incorrect objects.",
    violatedExpectation: "Recognition of a set of objects and attributes should preserve their pairings.",
    mechanism:
      "Distributed features and lossy token compression may preserve which attributes exist while weakening object-specific bindings.",
    alternatives: [
      "Question referent ambiguity",
      "Spatial relation error",
      "Language-side answer transposition",
    ],
    disconfirmingTest:
      "Keep the same feature inventory but permute only object–attribute assignments in balanced minimal pairs.",
    mitigations: [
      "Object-centric tokens",
      "Grounded intermediate representations",
      "Coordinate-aware decoding",
    ],
    severity: "foundational",
    reproducibility: "high",
    generator: "attribute-binding",
    accent: "cobalt",
    featured: true,
  },
  {
    id: "patch-phase-sensitivity",
    index: 3,
    title: "A one-pixel move changes the mind",
    shortTitle: "Patch-phase sensitivity",
    subtitle:
      "Equivalent images may be represented differently when content moves relative to an encoder’s patch lattice.",
    modalities: ["image"],
    stages: ["preprocessing", "tokenization", "vision-encoding"],
    capabilities: ["detection", "spatial-relations"],
    evidence: "hypothesis",
    sourceIds: ["vlms-blind", "eyes-wide-shut"],
    trigger: "Translate identical geometry across a known open-model patch grid without changing the answer.",
    symptom: "Accuracy oscillates with pixel offset, image padding, or resize dimensions.",
    violatedExpectation: "A small translation that preserves scene semantics should preserve the answer.",
    mechanism:
      "Hypothesis: non-overlapping patchification and stride can cause aliasing and redistribute weak features across tokens.",
    alternatives: ["Resize-kernel artifacts", "Positional encoding sensitivity", "Random decoding variation"],
    disconfirmingTest:
      "Sweep all phase offsets after calculating the exact post-resize patch lattice and test for periodicity.",
    mitigations: ["Overlapping stems", "Anti-aliasing", "Multi-scale or shift-averaged encoding"],
    severity: "high",
    reproducibility: "emerging",
    generator: "patch-phase",
    accent: "citron",
    featured: true,
  },
  {
    id: "counting-density-confound",
    index: 4,
    title: "Counting becomes texture",
    shortTitle: "Numerosity–density confound",
    subtitle: "The number of objects can be confused with occupied area, spacing, or visual density.",
    modalities: ["image", "video"],
    stages: ["vision-encoding", "object-state-representation"],
    capabilities: ["counting"],
    evidence: "literature-established",
    sourceIds: ["perceptionbench", "vlms-blind"],
    trigger:
      "Vary count while holding total occupied area constant, then vary density while holding count constant.",
    symptom: "Answers track aggregate ink or density rather than discrete object number.",
    violatedExpectation:
      "Numerosity should remain stable under irrelevant changes in object size and spacing.",
    mechanism:
      "Global texture and density statistics can be easier to encode than individuated object slots.",
    alternatives: [
      "Overlapping objects are not segmented",
      "Output token prior",
      "Approximate rather than exact counting strategy",
    ],
    disconfirmingTest:
      "Factorially cross count, object size, spacing, and occupied area with balanced labels.",
    mitigations: ["Object proposals", "Iterative marking", "Explicit counting supervision"],
    severity: "foundational",
    reproducibility: "high",
    generator: "numerosity-density",
    accent: "violet",
    featured: true,
  },
  {
    id: "small-object-erasure",
    index: 5,
    title: "Too small to survive",
    shortTitle: "Small-object erasure",
    subtitle: "An answer-bearing detail can vanish during resize, patch projection, or token compression.",
    modalities: ["image", "video"],
    stages: ["preprocessing", "tokenization", "compression"],
    capabilities: ["detection", "recognition", "ocr"],
    evidence: "literature-established",
    sourceIds: ["perceptionbench", "vlms-blind"],
    trigger:
      "Reduce only the angular or pixel size of a high-contrast target while preserving the wider scene.",
    symptom: "Performance drops abruptly below a scale threshold despite easy human zoom or inspection.",
    violatedExpectation: "A visible, unambiguous detail should remain available to answer a direct question.",
    mechanism:
      "Resizing and fixed-rate visual bottlenecks can mix the target with background before task-conditioned attention.",
    alternatives: ["Semantic unfamiliarity", "Crowding", "Question-dependent search failure"],
    disconfirmingTest: "Supply a crop at native scale and compare with an equal-resolution whole image.",
    mitigations: ["Dynamic resolution", "Foveated reacquisition", "High-resolution crops"],
    severity: "high",
    reproducibility: "high",
    generator: "small-object",
    accent: "teal",
    featured: true,
  },
  {
    id: "temporal-order-reversal",
    index: 6,
    title: "Before and after collapse",
    shortTitle: "Temporal-order reversal",
    subtitle: "A model may recognize both events while failing to distinguish A→B from B→A.",
    modalities: ["video"],
    stages: ["vision-encoding", "temporal-memory", "reasoning"],
    capabilities: ["temporal-order", "state-transitions"],
    evidence: "literature-established",
    sourceIds: ["tempcompass", "temporalbench", "videoqa-study", "arrow-time"],
    trigger: "Show a clip and its exact temporal reverse with counterbalanced questions.",
    symptom:
      "Answers remain unchanged under reversal or follow the more plausible narrative rather than observed order.",
    violatedExpectation: "Reversing an asymmetric event should reverse its temporal answer.",
    mechanism:
      "Order-invariant pooling, sparse frames, and caption-like training can privilege event presence over transition direction.",
    alternatives: [
      "Question ambiguity",
      "Frame timestamps omitted",
      "Physical prior overwhelms unusual reversed motion",
    ],
    disconfirmingTest:
      "Verify sampled evidence contains both states, then compare original, reversed, and shuffled controls.",
    mitigations: ["Timestamp supervision", "Arrow-of-time objectives", "Transition prediction"],
    severity: "foundational",
    reproducibility: "high",
    generator: "event-order",
    accent: "cobalt",
    featured: true,
  },
  {
    id: "identity-through-occlusion",
    index: 7,
    title: "The object that returned as another",
    shortTitle: "Identity through occlusion",
    subtitle: "Tracking can fail when visually similar entities disappear and re-emerge.",
    modalities: ["video"],
    stages: ["object-state-representation", "temporal-memory"],
    capabilities: ["identity-persistence", "tracking", "attribute-binding"],
    evidence: "behavioral-evidence",
    sourceIds: ["mvbench", "temporalbench", "video-mme-logical"],
    trigger:
      "Pass two distinguishable objects behind an occluder and independently swap their exit trajectories.",
    symptom: "The model reports the right final positions but attributes them to the wrong starting objects.",
    violatedExpectation:
      "Object identity should persist through temporary invisibility when motion permits an unambiguous assignment.",
    mechanism:
      "Frame-wise features and temporal compression may not maintain explicit object files across missing observations.",
    alternatives: [
      "Motion paths are genuinely ambiguous",
      "Colour attribute was lost",
      "Final localization error",
    ],
    disconfirmingTest: "Vary occlusion duration and crossing geometry while including visible-path controls.",
    mitigations: ["Track-centric memory", "Object permanence objectives", "Explicit trajectory slots"],
    severity: "foundational",
    reproducibility: "medium",
    generator: "identity-occlusion",
    accent: "violet",
    featured: true,
  },
  {
    id: "repeated-event-undercount",
    index: 8,
    title: "Once, twice, or many",
    shortTitle: "Repeated-event undercount",
    subtitle:
      "Repeated events can be represented as an occurrence type rather than an exact sequence of instances.",
    modalities: ["video"],
    stages: ["compression", "temporal-memory"],
    capabilities: ["event-frequency", "counting"],
    evidence: "behavioral-evidence",
    sourceIds: ["tempcompass", "temporalbench", "video-mme-v2"],
    trigger:
      "Vary the number and rhythm of identical flashes or collisions while holding total duration and appearance constant.",
    symptom: "The model reports a vague or systematically compressed count, especially at high rates.",
    violatedExpectation: "Exact event number should change monotonically with added visible instances.",
    mechanism:
      "Temporal pooling and semantic summarization may collapse repeated local events into a single 'repetition' feature.",
    alternatives: [
      "Events fall between sampled frames",
      "Motion blur merges events",
      "Numeral decoding bias",
    ],
    disconfirmingTest: "Compare native video with an explicit contact-sheet or timestamped-frame condition.",
    mitigations: ["Event boundary detection", "External counters", "Fine-grained temporal tokens"],
    severity: "high",
    reproducibility: "high",
    generator: "event-counting",
    accent: "vermillion",
    featured: true,
  },
  {
    id: "encoder-decoder-access-gap",
    index: 9,
    title: "Seen inside, unsayable outside",
    shortTitle: "Encoder–decoder access gap",
    subtitle:
      "A visual fact can be linearly decodable from the encoder yet unavailable through ordinary language prompting.",
    modalities: ["image"],
    stages: ["cross-modal-projection", "language-decoding"],
    capabilities: ["evidence-grounding", "spatial-relations"],
    evidence: "representation-evidence",
    sourceIds: ["vlms-blind"],
    trigger:
      "Use a task the model fails behaviorally, then train probes on intermediate visual representations.",
    symptom: "A lightweight probe succeeds where the full generative interface fails.",
    violatedExpectation:
      "Task-relevant information represented internally should be reliably accessible to downstream reasoning.",
    mechanism:
      "The multimodal projector, language training, or decoder policy may fail to route fine visual detail to output logits.",
    alternatives: [
      "Probe exploits dataset shortcuts",
      "Representation is decodable but not robustly usable",
      "Prompt mismatch",
    ],
    disconfirmingTest:
      "Use held-out generators, causal activation interventions, and probes at encoder, projector, and backbone stages.",
    mitigations: ["Perception-aware alignment", "Auxiliary readout losses", "Grounded intermediate tokens"],
    severity: "foundational",
    reproducibility: "medium",
    accent: "citron",
  },
  {
    id: "clip-blind-pairs",
    index: 10,
    title: "Different worlds, same embedding",
    shortTitle: "Contrastive feature collapse",
    subtitle:
      "Visually decisive differences can collapse when both images support nearly identical captions.",
    modalities: ["image"],
    stages: ["vision-encoding"],
    capabilities: ["recognition"],
    evidence: "representation-evidence",
    sourceIds: ["eyes-wide-shut"],
    trigger: "Construct pairs with similar global semantics but different low-level or relational facts.",
    symptom: "The encoder embeds them closely and downstream VLMs produce the same answer for both.",
    violatedExpectation: "Answer-changing visible differences should remain separable in the representation.",
    mechanism:
      "Instance-level image–text contrastive objectives reward caption equivalence more than exact geometry.",
    alternatives: [
      "Resolution loss",
      "Downstream projector collapse",
      "Insufficient paired training examples",
    ],
    disconfirmingTest:
      "Compare contrastive, self-supervised, and jointly language-trained visual encoders on identical pairs.",
    mitigations: ["Mixtures of visual features", "Fine-grained objectives", "Dense self-supervision"],
    severity: "foundational",
    reproducibility: "high",
    accent: "teal",
  },
];

// Literature-backed catalogue extensions. These entries intentionally avoid generator claims.
type CatalogueExtension = [
  string,
  string,
  string,
  string,
  FailureMode["modalities"],
  FailureMode["stages"],
  FailureMode["capabilities"],
  FailureMode["evidence"],
  string[],
];

const extensions: CatalogueExtension[] = [
  [
    "visible-spatial-relation",
    "Left becomes right",
    "Visible relation errors",
    "Directly visible left/right, above/below, inside/outside, and overlap relations are misread.",
    ["image"],
    ["vision-encoding", "reasoning"],
    ["spatial-relations"],
    "literature-established",
    ["perceptionbench", "vlms-blind", "dynasolidgeo"],
  ],
  [
    "depth-viewpoint-confusion",
    "The viewpoint trap",
    "Depth & viewpoint confusion",
    "Occlusion order, orientation, imagined viewpoint, and three-dimensional structure remain unreliable.",
    ["image", "video"],
    ["vision-encoding", "reasoning"],
    ["depth-viewpoint"],
    "literature-established",
    ["perceptionbench", "dynasolidgeo"],
  ],
  [
    "ocr-scale-rotation",
    "Letters at the edge of sight",
    "OCR under transformation",
    "Text recognition degrades sharply with scale, rotation, blur, occlusion, and unusual layout.",
    ["image", "video"],
    ["preprocessing", "vision-encoding"],
    ["ocr"],
    "literature-established",
    ["perceptionbench"],
  ],
  [
    "cross-region-integration",
    "The answer split across the page",
    "Cross-region integration",
    "Individually readable regions fail to combine into the required answer.",
    ["image", "multi-image"],
    ["context-integration", "reasoning"],
    ["cross-region-integration"],
    "literature-established",
    ["perceptionbench", "locovqa"],
  ],
  [
    "visual-comparison",
    "Almost the same",
    "Fine visual comparison",
    "Models misjudge same/different, larger/smaller, or subtle changes across elements.",
    ["image", "multi-image"],
    ["vision-encoding", "context-integration"],
    ["comparison"],
    "literature-established",
    ["perceptionbench", "eyes-wide-shut"],
  ],
  [
    "fine-grained-recognition",
    "The nearest familiar answer",
    "Fine-grained recognition",
    "Visually similar subtypes and entities are collapsed into a familiar parent category.",
    ["image", "video"],
    ["vision-encoding"],
    ["recognition"],
    "literature-established",
    ["perceptionbench"],
  ],
  [
    "visual-hallucination",
    "The object that was never there",
    "Visual hallucination",
    "The response asserts an object, label, or value unsupported by the media.",
    ["image", "video"],
    ["evidence-reliance", "language-decoding"],
    ["evidence-grounding"],
    "literature-established",
    ["perceptionbench", "videohallucer", "haven"],
  ],
  [
    "visual-distractor-overload",
    "The needle dissolves",
    "Visual distractor overload",
    "Relevant evidence becomes inaccessible as irrelevant images or visual regions accumulate.",
    ["multi-image", "interleaved"],
    ["context-integration", "evidence-reliance"],
    ["cross-region-integration"],
    "literature-established",
    ["locovqa"],
  ],
  [
    "temporal-grounding",
    "Right event, wrong moment",
    "Temporal grounding failure",
    "The model recognizes an event class but cannot locate when the answer-bearing instance occurred.",
    ["video"],
    ["frame-sampling", "context-integration"],
    ["localization", "temporal-order"],
    "literature-established",
    ["videoqa-study", "tempcompass"],
  ],
  [
    "motion-direction",
    "Motion without a direction",
    "Direction confusion",
    "Opposite motion directions elicit identical or physically preferred descriptions.",
    ["video"],
    ["vision-encoding", "reasoning"],
    ["duration-speed", "tracking"],
    "literature-established",
    ["tempcompass", "motionhalluc", "arrow-time"],
  ],
  [
    "speed-duration",
    "Fast, slow, long, short",
    "Speed and duration confusion",
    "Models conflate distance, speed, frame rate, and event duration.",
    ["video"],
    ["preprocessing", "reasoning"],
    ["duration-speed"],
    "literature-established",
    ["tempcompass", "temporalbench"],
  ],
  [
    "state-transition-memory",
    "The state that would not stay changed",
    "State-transition memory",
    "A model notices a change locally but later answers using the object’s earlier or typical state.",
    ["video"],
    ["temporal-memory", "object-state-representation"],
    ["state-transitions"],
    "behavioral-evidence",
    ["temporalbench", "video-mme-logical"],
  ],
  [
    "long-video-forgetting",
    "The vanishing beginning",
    "Long-video forgetting",
    "Evidence from early or sparse moments is lost as duration and distractor density increase.",
    ["video"],
    ["compression", "temporal-memory"],
    ["cross-region-integration"],
    "literature-established",
    ["video-mme-v2", "videoqa-study"],
  ],
  [
    "video-object-relation-hallucination",
    "A relation invented in motion",
    "Object–relation hallucination",
    "The model invents interactions or spatial relations not present in the clip.",
    ["video"],
    ["object-state-representation", "language-decoding"],
    ["spatial-relations", "evidence-grounding"],
    "literature-established",
    ["videohallucer", "haven"],
  ],
  [
    "spatiotemporal-sycophancy",
    "The video changes when challenged",
    "Spatiotemporal sycophancy",
    "Misleading feedback causes correct grounded judgments to reverse and acquire fabricated rationales.",
    ["video"],
    ["evidence-reliance", "calibration"],
    ["evidence-grounding"],
    "literature-established",
    ["sycophancy"],
  ],
  [
    "video-perturbation-insensitivity",
    "Change the video, keep the answer",
    "Video perturbation insensitivity",
    "Semantically important video changes affect answers less than superficial question or option changes.",
    ["video"],
    ["evidence-reliance", "evaluation-artifact"],
    ["evidence-grounding"],
    "literature-established",
    ["videoqa-study"],
  ],
  [
    "physical-arrow-of-time",
    "A world played backwards",
    "Arrow-of-time blindness",
    "Models fail to use the irreversible direction of physical processes when clips are reversed.",
    ["video"],
    ["reasoning", "temporal-memory"],
    ["temporal-order", "causality"],
    "literature-established",
    ["arrow-time"],
  ],
  [
    "kinematic-attribution",
    "The wrong limb moved",
    "Kinematic attribution error",
    "A genuine motion difference is assigned to the wrong body part, object, or phase.",
    ["video"],
    ["object-state-representation", "reasoning"],
    ["attribute-binding", "tracking"],
    "literature-established",
    ["motionhalluc"],
  ],
  [
    "causal-narrative-prior",
    "Plausible cause, absent evidence",
    "Causal narrative prior",
    "The model substitutes a plausible world narrative for the causal sequence actually shown.",
    ["video"],
    ["reasoning", "evidence-reliance"],
    ["causality"],
    "behavioral-evidence",
    ["video-mme-logical", "videoqa-study"],
  ],
  [
    "multi-question-inconsistency",
    "One video, incompatible answers",
    "Linked-answer inconsistency",
    "Answers to several questions about one clip are individually plausible but mutually incompatible.",
    ["video"],
    ["temporal-memory", "calibration"],
    ["evidence-grounding"],
    "literature-established",
    ["video-mme-v2"],
  ],
  [
    "answer-format-inflation",
    "Multiple choice knows more",
    "Format-dependent competence",
    "Performance changes sharply between multiple choice, yes/no, captioning, and open response for the same temporal fact.",
    ["video", "image"],
    ["language-decoding", "evaluation-artifact"],
    ["evidence-grounding"],
    "literature-established",
    ["tempcompass", "haven"],
  ],
  [
    "audiovisual-conflict",
    "When sound and sight disagree",
    "Audiovisual conflict",
    "The model may privilege one modality or fuse contradictory audiovisual evidence without calibrated uncertainty.",
    ["audiovisual"],
    ["context-integration", "evidence-reliance"],
    ["audiovisual-synchronization"],
    "hypothesis",
    ["mme-survey"],
  ],
];

for (const [offset, raw] of extensions.entries()) {
  const [id, title, shortTitle, subtitle, modalities, stages, capabilities, evidence, sourceIds] = raw;
  entries.push({
    id,
    index: 11 + offset,
    title,
    shortTitle,
    subtitle,
    modalities,
    stages,
    capabilities,
    evidence,
    sourceIds,
    trigger: "Use controlled minimal pairs that vary only the capability-bearing factor.",
    symptom: subtitle,
    violatedExpectation:
      "Answer-changing evidence should be represented and used, while irrelevant transformations should not change the answer.",
    mechanism:
      "The cited literature establishes the behavioral pattern; the responsible processing stage can differ by architecture and input pipeline.",
    alternatives: [
      "Input preprocessing",
      "Representation loss",
      "Cross-modal access failure",
      "Reasoning or decoding error",
    ],
    disconfirmingTest:
      "Intervene successively on acquisition, visual representation, textualized evidence, and output format to localize the earliest failure.",
    mitigations: [
      "Targeted diagnostic training",
      "Adaptive evidence acquisition",
      "Explicit grounded representations",
    ],
    severity: id.includes("format") ? "moderate" : "high",
    reproducibility: evidence === "hypothesis" ? "emerging" : "medium",
    accent: (["vermillion", "cobalt", "citron", "violet", "teal"] as const)[offset % 5],
  });
}

export const failureModes: FailureMode[] = entries.map((entry) => ({
  ...entry,
  affectedModels:
    entry.affectedModels ??
    "Behavior is reported only for the model cohorts in the cited studies; the atlas has not yet established a current cross-model affected set.",
}));
export const failureModesById = new Map(failureModes.map((entry) => [entry.id, entry]));

export const modalities = ["image", "video", "audiovisual", "multi-image", "interleaved"] as const;

export const humanize = (value: string) =>
  value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
