import type { Citation } from "./types";

export const citations: Citation[] = [
  {
    id: "gemini-video-docs",
    title: "Gemini API: Video Understanding",
    authors: "Google AI for Developers",
    year: 2026,
    url: "https://ai.google.dev/gemini-api/docs/video-understanding",
    note: "Official interface documentation discloses default one-frame-per-second visual sampling, video token budgets, and the risk of losing fast changes.",
    retrieved: "2026-08-30",
  },
  {
    id: "qwen3-vl",
    title: "Qwen3-VL Technical Report",
    authors: "Bai et al.",
    year: 2025,
    url: "https://arxiv.org/abs/2511.21631",
    note: "Documents the current Qwen visual architecture, interleaved multimodal position encoding, multi-level visual features, and long-video training.",
    retrieved: "2026-08-30",
  },
  {
    id: "kimi-k3",
    title: "Kimi K3: Open Frontier Intelligence",
    authors: "Moonshot AI et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2607.24653",
    note: "Technical report for a 2.8T-parameter open native-multimodal MoE using Kimi Delta Attention, Attention Residuals, and a million-token context.",
    retrieved: "2026-08-30",
  },
  {
    id: "moment-video",
    title: "Moment-Video: Diagnosing Temporal Fidelity of Video MLLMs on Momentary Visual Events",
    authors: "Liu et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2606.02522",
    note: "One thousand human-verified questions isolate brief answer-critical events; the strongest reported model reaches 39.6% overall.",
    retrieved: "2026-08-30",
  },
  {
    id: "ec-bench",
    title: "Diagnosing Long-Video Quantitative Reasoning via Enumeration and Counting",
    authors: "Tsuchiya et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2603.29943",
    note: "Separates enumeration, evidence grounding, and count aggregation; reports a large human-model gap across 22 MLLMs.",
    retrieved: "2026-08-30",
  },
  {
    id: "synflash",
    title: "Shot-Aware Frame Sampling for Video Understanding",
    authors: "Zhao et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2603.17374",
    note: "Introduces SynFlash, a controllable synthetic test of sub-second anomalies, and evaluates a sampler designed to preserve brief changes.",
    retrieved: "2026-08-30",
  },
  {
    id: "vgenst",
    title: "VGenST-Bench: A Benchmark for Spatio-Temporal Reasoning via Active Video Synthesis",
    authors: "Park et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2605.22570",
    note: "Uses active video synthesis plus human quality control to decouple visual perception from higher-level spatiotemporal reasoning.",
    retrieved: "2026-08-30",
  },
  {
    id: "video-uq-failure-modes",
    title: "Video-UQ Failure-Mode Benchmarks",
    authors: "LEAP-UQ",
    year: 2026,
    url: "https://huggingface.co/LEAP-UQ/video-uq-failure-mode-benchmarks",
    note: "Controlled intervention suites distinguish language-prior, sampling, evidence-extraction, and temporal-grounding failures across five open VideoLLMs.",
    retrieved: "2026-08-30",
  },
  {
    id: "frame-sampling-matters",
    title: "Frame Sampling Strategies Matter: A Benchmark for Small Vision-Language Models",
    authors: "Brkic et al.",
    year: 2025,
    url: "https://arxiv.org/abs/2509.14769",
    note: "Controls frame budget and sampling policy across four open video VLMs, showing that preprocessing can change model comparisons.",
    retrieved: "2026-08-30",
  },
  {
    id: "perceptionbench",
    title: "PerceptionBench: Evaluating Atomic Visual Perception in Multimodal Large Language Models",
    authors: "Lin et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2607.24957",
    note: "Failure-attribution taxonomy induced from 42 benchmarks; ten atomic perception capabilities and 3,000 verified questions.",
    retrieved: "2026-08-30",
  },
  {
    id: "eyes-wide-shut",
    title: "Eyes Wide Shut? Exploring the Visual Shortcomings of Multimodal LLMs",
    authors: "Tong et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2401.06209",
    note: "Introduces CLIP-blind image pairs and MMVP; connects downstream errors to contrastive visual representations.",
    retrieved: "2026-08-30",
  },
  {
    id: "vlms-blind",
    title: "Vision Language Models are Blind: Failing to Translate Detailed Visual Features into Words",
    authors: "Rahmanzadehgervi et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2407.06581",
    note: "Simple synthetic visual tasks plus linear probes separating encoder information from language decoding.",
    retrieved: "2026-08-30",
  },
  {
    id: "locovqa",
    title:
      "Losing Visual Needles in Image Haystacks: Vision Language Models are Easily Distracted in Short and Long Contexts",
    authors: "Sharma et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2406.16851",
    note: "Dynamic generator showing rapid degradation as irrelevant visual context grows.",
    retrieved: "2026-08-30",
  },
  {
    id: "videoqa-study",
    title: "VideoQA in the Era of LLMs: An Empirical Study",
    authors: "Xiao et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2408.04223",
    note: "Documents temporal-order and grounding deficits, video-perturbation insensitivity, and sensitivity to answer wording.",
    retrieved: "2026-08-30",
  },
  {
    id: "tempcompass",
    title: "TempCompass: Do Video LLMs Really Understand Videos?",
    authors: "Liu et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2403.00476",
    note: "Separates temporal perception into action, direction, speed, order, and attribute-change dimensions across formats.",
    retrieved: "2026-08-30",
  },
  {
    id: "temporalbench",
    title: "TemporalBench: Benchmarking Fine-grained Temporal Understanding for Multimodal Video Models",
    authors: "Cai et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2410.10818",
    note: "Approximately 10K questions grounded in human annotations of fine-grained temporal dynamics.",
    retrieved: "2026-08-30",
  },
  {
    id: "mvbench",
    title: "MVBench: A Comprehensive Multi-modal Video Understanding Benchmark",
    authors: "Li et al.",
    year: 2023,
    url: "https://arxiv.org/abs/2311.17005",
    note: "Twenty video tasks intentionally requiring more than a single frame.",
    retrieved: "2026-08-30",
  },
  {
    id: "video-mme-v2",
    title: "Video-MME-v2: Towards the Next Stage in Benchmarks for Comprehensive Video Understanding",
    authors: "Fu et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2604.05015",
    note: "Progressive tri-level evaluation of robust and faithful video understanding using linked questions.",
    retrieved: "2026-08-30",
  },
  {
    id: "video-mme-logical",
    title: "Video-MME-Logical: A Controlled Diagnostic Benchmark for Video Temporal-Logical Reasoning",
    authors: "Kwan et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2606.27828",
    note: "Controlled tests requiring evidence maintenance, update, and composition as visual states evolve.",
    retrieved: "2026-08-30",
  },
  {
    id: "videohallucer",
    title: "VideoHallucer: Evaluating Intrinsic and Extrinsic Hallucinations in Large Video-Language Models",
    authors: "Wang et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2406.16338",
    note: "Taxonomy of intrinsic and extrinsic video hallucinations, including object-relation, temporal, and semantic errors.",
    retrieved: "2026-08-30",
  },
  {
    id: "haven",
    title: "Exploring Hallucination of Large Multimodal Models in Video Understanding",
    authors: "Gao et al.",
    year: 2025,
    url: "https://arxiv.org/abs/2503.19622",
    note: "HAVEN organizes 6K questions across hallucination causes, aspects, and question formats and studies seven factors.",
    retrieved: "2026-08-30",
  },
  {
    id: "sycophancy",
    title: "Spatiotemporal Sycophancy: Negation-Based Gaslighting in Video Large Language Models",
    authors: "Tang et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2604.17873",
    note: "Shows models retracting correct grounded judgments and fabricating spatial or temporal justifications after misleading feedback.",
    retrieved: "2026-08-30",
  },
  {
    id: "motionhalluc",
    title: "MotionHalluc: Diagnosing Kinematic Hallucinations in Fine-Grained Motion Reasoning",
    authors: "Guo et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2606.23061",
    note: "Separates directional, attributional, and temporal hallucinations in paired-video motion comparison.",
    retrieved: "2026-08-30",
  },
  {
    id: "arrow-time",
    title: "Seeing the Arrow of Time in Large Multimodal Models",
    authors: "Xue et al.",
    year: 2025,
    url: "https://arxiv.org/abs/2506.03340",
    note: "Probes whether models perceive and use temporal directionality under video reversal.",
    retrieved: "2026-08-30",
  },
  {
    id: "rekey",
    title: "REKEY: Metadata-Grounded Visual-Key Regeneration for Contamination-Resilient VQA Evaluation",
    authors: "Lin et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2606.20736",
    note: "Regenerates answer-bearing details at evaluation time and finds large gaps between original and renewed benchmark items.",
    retrieved: "2026-08-30",
  },
  {
    id: "dynasolidgeo",
    title: "DynaSolidGeo: A Dynamic Benchmark for Genuine Spatial Mathematical Reasoning of VLMs",
    authors: "Wu et al.",
    year: 2025,
    url: "https://arxiv.org/abs/2510.22340",
    note: "Procedurally generates unbounded solid-geometry variants and evaluates both answers and reasoning processes.",
    retrieved: "2026-08-30",
  },
  {
    id: "revelio",
    title: "Revealing Interpretable Failure Modes of VLMs",
    authors: "Chaudhary et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2605.12674",
    note: "Searches interpretable concept combinations for consistent failures in driving and robotics.",
    retrieved: "2026-08-30",
  },
  {
    id: "failure-rl",
    title: "Discovering Failure Modes in Vision-Language Models using RL",
    authors: "Jain et al.",
    year: 2026,
    url: "https://arxiv.org/abs/2604.04733",
    note: "Trains a questioner to adaptively elicit fine-grained and compositional blind spots from a candidate VLM.",
    retrieved: "2026-08-30",
  },
  {
    id: "mme-survey",
    title: "MME-Survey: A Comprehensive Survey on Evaluation of Multimodal LLMs",
    authors: "Fu et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2411.15296",
    note: "Broad survey of capability benchmarks, construction practices, metrics, judges, and evaluation toolkits.",
    retrieved: "2026-08-30",
  },
  {
    id: "vhelm",
    title: "VHELM: A Holistic Evaluation of Vision Language Models",
    authors: "Lee et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2410.07112",
    note: "Standardizes evaluation across visual perception, reasoning, robustness, fairness, safety, and other dimensions, with released raw generations.",
    retrieved: "2026-08-30",
  },
  {
    id: "lmms-eval",
    title: "LMMs-Eval: Reality Check on the Evaluation of Large Multimodal Models",
    authors: "Zhang et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2407.12772",
    note: "Introduces LMMS-EVAL, the lighter suite, and Multimodal LiveBench while making the coverage–cost–contamination trade-off explicit.",
    retrieved: "2026-08-30",
  },
  {
    id: "video-mme",
    title:
      "Video-MME: The First-Ever Comprehensive Evaluation Benchmark of Multi-modal LLMs in Video Analysis",
    authors: "Fu et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2405.21075",
    note: "Evaluates 900 videos across durations, domains, subtitles, and audio, establishing a broad predecessor to the controlled v2 diagnostics.",
    retrieved: "2026-08-30",
  },
  {
    id: "wildvision",
    title: "WildVision: Evaluating Vision-Language Models in the Wild with Human Preferences",
    authors: "Lu et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2406.11069",
    note: "Uses real user interactions and preference judgments; its analysis surfaces spatial, subtle-context, hallucination, and expert-domain weaknesses.",
    retrieved: "2026-08-30",
  },
  {
    id: "visionarena",
    title: "VisionArena: 230K Real World User-VLM Conversations with Preference Labels",
    authors: "Chou et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2412.08687",
    note: "Large real-world conversation and preference corpus that complements controlled diagnostics with ecological user demand.",
    retrieved: "2026-08-30",
  },
  {
    id: "qwen2-vl",
    title: "Qwen2-VL: Enhancing Vision-Language Model's Perception of the World at Any Resolution",
    authors: "Wang et al.",
    year: 2024,
    url: "https://arxiv.org/abs/2409.12191",
    note: "Documents dynamic visual resolution, multimodal rotary position encoding, and a unified image/video processing paradigm in an open model family.",
    retrieved: "2026-08-30",
  },
  {
    id: "divprune",
    title: "DivPrune: Diversity-based Visual Token Pruning for Large Multimodal Models",
    authors: "Ranjbar Alvar et al.",
    year: 2025,
    url: "https://arxiv.org/abs/2503.02175",
    venue: "CVPR 2025",
    note: "Studies diversity-based visual-token selection under aggressive compression across image and video tasks.",
    retrieved: "2026-08-30",
  },
  {
    id: "traversalbench",
    title: "TraversalBench: Challenging Paths to Follow for Vision Language Models",
    authors: "Petrova, Chen, and Soljačić",
    year: 2026,
    url: "https://arxiv.org/abs/2604.10999",
    note: "Controlled exact visual path traversal showing that self-intersections dominate errors and localize breakdown near the first crossing.",
    retrieved: "2026-09-01",
  },
  {
    id: "atp-llava",
    title: "ATP-LLaVA: Adaptive Token Pruning for Large Vision Language Models",
    authors: "Ye et al.",
    year: 2025,
    url: "https://openaccess.thecvf.com/content/CVPR2025/html/Ye_ATP-LLaVA_Adaptive_Token_Pruning_for_Large_Vision_Language_Models_CVPR_2025_paper.html",
    venue: "CVPR 2025",
    note: "Adapts pruning rates to layerwise visual-token redundancy instead of imposing one fixed compression ratio.",
    retrieved: "2026-08-30",
  },
];

export const citationsById = new Map(citations.map((citation) => [citation.id, citation]));
