import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const collisionTimingVersion = "spatiotemporal-collision-disambiguation-v1"; export const collisionAnswers = ["A+B", "A+C", "B+D", "C+D"] as const; const pairs = [[0, 1], [0, 2], [1, 3], [2, 3]] as const;
export const collisionCandidateSchema = z.object({ id: z.string(), cellId: z.string(), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("spatiotemporal-collision-disambiguation"), question: z.string(), answerOptions: z.array(z.enum(collisionAnswers)).length(4), expectedAnswer: z.enum(collisionAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ collidingPair: z.number().int().min(0).max(3), offsetsMs: z.array(z.number().int()).length(4), videoDurationMs: z.literal(11200), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) }); export type CollisionCandidate = z.infer<typeof collisionCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => ((state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000); } function shuffled<T>(values: readonly T[], random: () => number) { const out = [...values]; for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [out[i], out[j]] = [out[j]!, out[i]!]; } return out; }
export function createCollisionCandidate(input: { split: "discovery" | "confirmatory"; seed: number; collidingPair: number; visualVariant?: number }) { const random = rng(input.seed), offsetsMs = Array.from({ length: 4 }, (_, i) => i === input.collidingPair ? 0 : (random() < .5 ? -1 : 1) * (470 + Math.floor(random() * 180))), visualVariant = input.visualVariant ?? input.seed % 229; return collisionCandidateSchema.parse({ id: `cl-${sha256(JSON.stringify({ ...input, offsetsMs, visualVariant })).slice(0, 16)}`, cellId: "cell-four-crossing-trials-one-collision", split: input.split, seed: input.seed, failureModeId: "spatiotemporal-collision-disambiguation", question: "Which labeled pair actually COLLIDES (occupies the center at the same time)? The other pairs cross the same spatial point at different times.", answerOptions: shuffled(collisionAnswers, rng(input.seed + 43)), expectedAnswer: collisionAnswers[input.collidingPair], humanSolvability: "unverified", parameters: { collidingPair: input.collidingPair, offsetsMs, videoDurationMs: 11200, fps: 30, visualVariant } }); }
export function createCollisionGrid() { const out: CollisionCandidate[] = []; let seed = 3_700_000; for (let rep = 0; rep < 2; rep++) for (let collidingPair = 0; collidingPair < 4; collidingPair++) out.push(createCollisionCandidate({ split: "discovery", seed: seed++, collidingPair, visualVariant: rep * 4 + collidingPair })); return out; }
const colors = ["#df3c30", "#2466cc", "#1d9b5f", "#9146c7"];
function progress(timestamp: number, offset: number) { return Math.max(0, Math.min(1, (timestamp - 300 - offset) / 1400)); }
export function renderCollisionSvg(candidate: CollisionCandidate, timestampMs: number) { const phaseStart = 700, phaseMs = 2500, trial = Math.floor((timestampMs - phaseStart) / phaseMs), local = (timestampMs - phaseStart) - trial * phaseMs, pair = trial >= 0 && trial < 4 ? pairs[trial] : null, p1 = progress(local, 0), p2 = progress(local, candidate.parameters.offsetsMs[Math.max(0, trial)] ?? 0), x1 = 100 + 520 * p1, y1 = 355, x2 = 360, y2 = 95 + 520 * p2, balls = pair ? `<circle cx="${x1}" cy="${y1}" r="34" fill="${colors[pair[0]]}" stroke="#202322" stroke-width="4"/><text x="${x1}" y="${y1 + 11}" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700" fill="#fff">${String.fromCharCode(65 + pair[0])}</text><circle cx="${x2}" cy="${y2}" r="34" fill="${colors[pair[1]]}" stroke="#202322" stroke-width="4"/><text x="${x2}" y="${y2 + 11}" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700" fill="#fff">${String.fromCharCode(65 + pair[1])}</text>` : "", status = trial < 0 ? "GET READY" : trial < 4 ? `PAIR ${collisionAnswers[trial]} · TRIAL ${trial + 1} OF 4` : "WHICH PAIR COLLIDED?"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="700"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="46" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">SAME PLACE — BUT SAME TIME?</text><text x="360" y="80" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Only one pair reaches the central intersection simultaneously</text><text x="360" y="125" text-anchor="middle" font-family="Arial" font-size="22" font-weight="700">${status}</text><rect x="65" y="160" width="590" height="480" rx="24" fill="#fffef9" stroke="#202322" stroke-width="5"/><line x1="100" y1="355" x2="620" y2="355" stroke="#b8b4ab" stroke-width="7"/><line x1="360" y1="195" x2="360" y2="615" stroke="#b8b4ab" stroke-width="7"/><circle cx="360" cy="355" r="8" fill="#202322"/>${balls}</svg>`; }
