import { z } from "zod";import{sha256}from"../evaluation/hash";
export const dynamicStateVersion="dynamic-state-accumulation-v1";export const stateAnswers=["RED","GREEN","BLUE","PURPLE"]as const;
export const dynamicStateCandidateSchema=z.object({id:z.string(),cellId:z.string(),split:z.enum(["discovery","confirmatory"]),seed:z.number().int().nonnegative(),failureModeId:z.literal("latent-dynamic-state-accumulation"),question:z.string(),answerOptions:z.array(z.enum(stateAnswers)).length(4),expectedAnswer:z.enum(stateAnswers),humanSolvability:z.literal("unverified"),parameters:z.object({targetState:z.number().int().min(0).max(3),initialState:z.number().int().min(0).max(3),vx:z.number(),vy:z.number(),videoDurationMs:z.literal(10000),motionEndMs:z.literal(8200),fps:z.literal(30),visualVariant:z.number().int().nonnegative()})});export type DynamicStateCandidate=z.infer<typeof dynamicStateCandidateSchema>;
function rng(seed:number){let s=seed>>>0;return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/0x1_0000_0000);}function shuffle<T>(v:readonly T[],r:()=>number){const a=[...v];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j]!,a[i]!];}return a;}
type Event={timeMs:number;kind:"vertical"|"horizontal"};
function reflectPosition(start:number,velocity:number,min:number,max:number,t:number){const span=max-min,raw=start-min+velocity*t,period=span*2,wrapped=((raw%period)+period)%period;return wrapped<=span?min+wrapped:max-(wrapped-span);}
export function dynamicStateEventsFrom(seed:number,vx:number,vy:number,endMs:number){const random=rng(seed+77);const startX=220+random()*220,startY=230+random()*160;const events:Event[]=[];for(const[kind,start,v,min,max]of[["vertical",startX,vx,90,630],["horizontal",startY,vy,150,540]]as const){let position=start,time=0,direction=Math.sign(v);const speed=Math.abs(v);while(time<endMs/1000){const distance=direction>0?max-position:position-min;time+=distance/speed;if(time*1000<endMs)events.push({timeMs:time*1000,kind});position=direction>0?max:min;direction*=-1;}}return events.sort((a,b)=>a.timeMs-b.timeMs);}
export function createDynamicStateCandidate(input:{split:"discovery"|"confirmatory";seed:number;targetState:number;visualVariant?:number}){const random=rng(input.seed),vx=78+random()*22,vy=54+random()*19,events=dynamicStateEventsFrom(input.seed,vx,vy,8200);const increment=events.reduce((sum,event)=>sum+(event.kind==="vertical"?1:2),0)%4,initialState=(input.targetState-increment+4)%4,visualVariant=input.visualVariant??input.seed%151;return dynamicStateCandidateSchema.parse({id:`ds-${sha256(JSON.stringify({...input,vx,vy,initialState,visualVariant})).slice(0,16)}`,cellId:"cell-hidden-four-state-wall-updates",split:input.split,seed:input.seed,failureModeId:"latent-dynamic-state-accumulation",question:"What is the ball's hidden final state? Cycle RED→GREEN→BLUE→PURPLE→RED. Each VERTICAL-wall bounce advances 1 step; each HORIZONTAL-wall bounce advances 2 steps.",answerOptions:shuffle(stateAnswers,rng(input.seed+5)),expectedAnswer:stateAnswers[input.targetState],humanSolvability:"unverified",parameters:{targetState:input.targetState,initialState,vx,vy,videoDurationMs:10000,motionEndMs:8200,fps:30,visualVariant}});}
export function createDynamicStateDiscoveryGrid(){const r:DynamicStateCandidate[]=[];let seed=2_300_000;for(let rep=0;rep<2;rep++)for(let targetState=0;targetState<4;targetState++)r.push(createDynamicStateCandidate({split:"discovery",seed:seed++,targetState,visualVariant:rep*4+targetState}));return r;}
export function createDynamicStateHoldout(){const r:DynamicStateCandidate[]=[];let seed=2_310_000;for(let rep=0;rep<4;rep++)for(let targetState=0;targetState<4;targetState++)r.push(createDynamicStateCandidate({split:"confirmatory",seed:seed++,targetState,visualVariant:300+rep*4+targetState}));return r;}
export function dynamicFinalState(candidate:DynamicStateCandidate){return(candidate.parameters.initialState+dynamicStateEventsFrom(candidate.seed,candidate.parameters.vx,candidate.parameters.vy,candidate.parameters.motionEndMs).reduce((s,e)=>s+(e.kind==="vertical"?1:2),0))%4;}
const fills=["#df3c30","#1d9b5f","#2466cc","#9146c7"];
export function renderDynamicStateSvg(candidate:DynamicStateCandidate,timestampMs:number,control=false){const random=rng(candidate.seed+77),startX=220+random()*220,startY=230+random()*160,t=Math.min(timestampMs,candidate.parameters.motionEndMs)/1000,x=reflectPosition(startX,candidate.parameters.vx,90,630,t),y=reflectPosition(startY,candidate.parameters.vy,150,540,t);const events=dynamicStateEventsFrom(candidate.seed,candidate.parameters.vx,candidate.parameters.vy,candidate.parameters.motionEndMs),recent=events.find(e=>timestampMs>=e.timeMs&&timestampMs<e.timeMs+230);const currentState=(candidate.parameters.initialState+events.filter(e=>e.timeMs<=Math.min(timestampMs,candidate.parameters.motionEndMs)).reduce((s,e)=>s+(e.kind==="vertical"?1:2),0))%4;const hidden=!control&&timestampMs>=candidate.parameters.motionEndMs;const initial=timestampMs<1100;const ball=hidden?`<rect x="70" y="130" width="580" height="430" rx="22" fill="#202322"/><text x="360" y="350" text-anchor="middle" font-family="Arial" font-size="34" font-weight="700" fill="#fff">STATE HIDDEN</text>`:`<rect x="70" y="130" width="580" height="430" rx="22" fill="#fffef9" stroke="#202322" stroke-width="7"/><circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="31" fill="${control?fills[currentState]:initial?fills[candidate.parameters.initialState]:"#59605d"}" stroke="#fff" stroke-width="4"/>`;const flash=recent&&!hidden?`<rect x="${recent.kind==="vertical"?(x<360?66:626):70}" y="${recent.kind==="horizontal"?(y<350?126:536):130}" width="${recent.kind==="vertical"?28:580}" height="${recent.kind==="horizontal"?28:430}" fill="#f4d934" opacity=".9"/>`:"";return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="42" text-anchor="middle" font-family="Arial" font-size="23" font-weight="700">${control?"CONTROL: STATE REMAINS VISIBLE":"TRACK THE HIDDEN COLOR STATE"}</text><text x="360" y="77" text-anchor="middle" font-family="Arial" font-size="18">VERTICAL +1 · HORIZONTAL +2</text><text x="360" y="105" text-anchor="middle" font-family="Arial" font-size="16" fill="#59605d">RED → GREEN → BLUE → PURPLE → RED</text>${ball}${flash}<text x="360" y="610" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">${control?`Current state: ${stateAnswers[currentState]}`:"The ball shows its initial color briefly, then turns gray."}</text></svg>`;}
