import { z } from "zod"; import { sha256 } from "../evaluation/hash"; import { indexedSuccessorAnswers, indexedSymbolSvg } from "./indexed-successor-hard";
export const extremeIndexedVersion = "indexed-successor-v4"; const sequenceSchema = z.array(z.number().int().min(0).max(4)).length(80);
export const extremeIndexedCandidateSchema = z.object({ id: z.string(), cellId: z.literal("cell-eighty-event-ninth-marker-successor"), split: z.literal("discovery"), seed: z.number().int().nonnegative(), failureModeId: z.literal("ordinal-event-successor-binding"), question: z.string(), answerOptions: z.array(z.enum(indexedSuccessorAnswers)).length(4), expectedAnswer: z.enum(indexedSuccessorAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ answerIndex: z.number().int().min(0).max(3), sequence: sequenceSchema, targetOccurrence: z.literal(9), videoDurationMs: z.literal(18_500), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) }); export type ExtremeIndexedCandidate = z.infer<typeof extremeIndexedCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; } function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function extremeIndexedSuccessor(values: readonly number[]) { let seen = 0; for (let i = 0; i < values.length - 1; i += 1) if (values[i] === 4 && ++seen === 9) return values[i + 1]!; throw new Error("Missing ninth successor"); }
function makeSequence(seed: number, answerIndex: number) { for (let attempt = 0; attempt < 100_000; attempt += 1) { const random = rng(seed + attempt * 1877), values = Array.from({ length: 80 }, () => Math.floor(random() * 5)); if (values.filter((value) => value === 4).length >= 11 && extremeIndexedSuccessor(values) === answerIndex) return values; } throw new Error("Could not construct extreme indexed sequence"); }
export function createExtremeIndexedCandidate(input: { seed: number; answerIndex: number; visualVariant: number }) { const values = makeSequence(input.seed + 83, input.answerIndex); return extremeIndexedCandidateSchema.parse({ id: `isx4-${sha256(JSON.stringify({ ...input, values })).slice(0, 16)}`, cellId: "cell-eighty-event-ninth-marker-successor", split: "discovery", seed: input.seed, failureModeId: "ordinal-event-successor-binding", question: "Which symbol appears IMMEDIATELY AFTER the NINTH white diamond in the complete stream?", answerOptions: shuffled(indexedSuccessorAnswers, rng(input.seed + 43)), expectedAnswer: indexedSuccessorAnswers[input.answerIndex], humanSolvability: "unverified", parameters: { answerIndex: input.answerIndex, sequence: values, targetOccurrence: 9, videoDurationMs: 18_500, fps: 30, visualVariant: input.visualVariant } }); }
export function createExtremeIndexedGrid() { const output: ExtremeIndexedCandidate[] = []; let seed = 5_320_000; for (let replicate = 0; replicate < 2; replicate += 1) for (let answer = 0; answer < 4; answer += 1) output.push(createExtremeIndexedCandidate({ seed: seed++, answerIndex: answer, visualVariant: replicate * 4 + answer })); return output; }
export function renderExtremeIndexedSvg(candidate: ExtremeIndexedCandidate, timestampMs: number) { const start = 800, eventMs = 200, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 80 && local < 155 ? candidate.parameters.sequence[index] : -1, status = index < 0 ? "GET READY" : index < 80 ? `EVENT ${index + 1} OF 80` : "STREAM COMPLETE"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="44" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">FIND THE NINTH DIAMOND'S SUCCESSOR</text><text x="360" y="83" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Count white diamonds; remember only what follows number nine</text><text x="360" y="132" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${active >= 0 ? indexedSymbolSvg(active, 360, 360, 190) : ""}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">${index >= 80 ? "Which symbol followed the ninth diamond?" : "Keep counting carefully"}</text></svg>`; }
