import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const indexedSuccessorVersion = "indexed-successor-v3"; export const indexedSuccessorAnswers = ["CIRCLE", "TRIANGLE", "SQUARE", "STAR"] as const; const eventSequence = z.array(z.number().int().min(0).max(4)).length(60);
export const indexedSuccessorCandidateSchema = z.object({ id: z.string(), cellId: z.literal("cell-sixty-event-sixth-marker-successor"), split: z.literal("discovery"), seed: z.number().int().nonnegative(), failureModeId: z.literal("ordinal-event-successor-binding"), question: z.string(), answerOptions: z.array(z.enum(indexedSuccessorAnswers)).length(4), expectedAnswer: z.enum(indexedSuccessorAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ answerIndex: z.number().int().min(0).max(3), sequence: eventSequence, targetOccurrence: z.literal(6), videoDurationMs: z.literal(16_500), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) }); export type IndexedSuccessorCandidate = z.infer<typeof indexedSuccessorCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; } function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function indexedSuccessor(values: readonly number[], occurrence = 6) { let seen = 0; for (let i = 0; i < values.length - 1; i += 1) if (values[i] === 4 && ++seen === occurrence) return values[i + 1]!; throw new Error("Missing indexed successor"); }
function makeSequence(seed: number, answerIndex: number) { for (let attempt = 0; attempt < 100_000; attempt += 1) { const random = rng(seed + attempt * 1877), values = Array.from({ length: 60 }, () => Math.floor(random() * 5)); if (values.filter((value) => value === 4).length >= 8 && indexedSuccessor(values) === answerIndex) return values; } throw new Error("Could not construct indexed successor sequence"); }
export function createIndexedSuccessorCandidate(input: { seed: number; answerIndex: number; visualVariant: number }) { const values = makeSequence(input.seed + 83, input.answerIndex); return indexedSuccessorCandidateSchema.parse({ id: `isx-${sha256(JSON.stringify({ ...input, values })).slice(0, 16)}`, cellId: "cell-sixty-event-sixth-marker-successor", split: "discovery", seed: input.seed, failureModeId: "ordinal-event-successor-binding", question: "Which symbol appears IMMEDIATELY AFTER the SIXTH white diamond in the complete stream?", answerOptions: shuffled(indexedSuccessorAnswers, rng(input.seed + 43)), expectedAnswer: indexedSuccessorAnswers[input.answerIndex], humanSolvability: "unverified", parameters: { answerIndex: input.answerIndex, sequence: values, targetOccurrence: 6, videoDurationMs: 16_500, fps: 30, visualVariant: input.visualVariant } }); }
export function createIndexedSuccessorGrid() { const output: IndexedSuccessorCandidate[] = []; let seed = 5_300_000; for (let replicate = 0; replicate < 2; replicate += 1) for (let answer = 0; answer < 4; answer += 1) output.push(createIndexedSuccessorCandidate({ seed: seed++, answerIndex: answer, visualVariant: replicate * 4 + answer })); return output; }
const colors = ["#2466cc", "#1d9b5f", "#df3c30", "#9146c7", "#fffef9"];
function symbolSvg(symbol: number, x: number, y: number, size: number) { if (symbol === 0) return `<circle cx="${x}" cy="${y}" r="${size * .43}" fill="${colors[symbol]}"/>`; if (symbol === 1) return `<polygon points="${x},${y - size * .5} ${x - size * .48},${y + size * .42} ${x + size * .48},${y + size * .42}" fill="${colors[symbol]}"/>`; if (symbol === 2) return `<rect x="${x - size * .42}" y="${y - size * .42}" width="${size * .84}" height="${size * .84}" fill="${colors[symbol]}"/>`; if (symbol === 3) { const points = Array.from({ length: 10 }, (_, i) => { const angle = -Math.PI / 2 + i * Math.PI / 5, radius = i % 2 ? size * .2 : size * .5; return `${x + Math.cos(angle) * radius},${y + Math.sin(angle) * radius}`; }).join(" "); return `<polygon points="${points}" fill="${colors[symbol]}"/>`; } return `<polygon points="${x},${y - size * .5} ${x + size * .5},${y} ${x},${y + size * .5} ${x - size * .5},${y}" fill="#fffef9" stroke="#202322" stroke-width="7"/>`; }
export function renderIndexedSuccessorSvg(candidate: IndexedSuccessorCandidate, timestampMs: number) { const start = 800, eventMs = 240, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 60 && local < 190 ? candidate.parameters.sequence[index] : -1, diamonds = candidate.parameters.sequence.slice(0, Math.max(0, Math.min(60, index + 1))).filter((value) => value === 4).length, status = index < 0 ? "GET READY" : index < 60 ? `EVENT ${index + 1} OF 60` : "STREAM COMPLETE"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="44" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">FIND THE SIXTH DIAMOND'S SUCCESSOR</text><text x="360" y="83" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Count white diamonds; remember only what follows number six</text><text x="360" y="132" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${active >= 0 ? symbolSvg(active, 360, 360, 190) : ""}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">${index >= 60 ? "Which symbol came immediately after the sixth diamond?" : "Keep counting carefully"}</text></svg>`; }
