import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const intervalContainmentVersion = "temporal-interval-containment-v1"; export const intervalAnswers = ["A", "B", "C", "D"] as const; const intervalSchema = z.tuple([z.number().int().min(0).max(17), z.number().int().min(1).max(18)]);
export const intervalCandidateSchema = z.object({ id: z.string(), cellId: z.string(), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("temporal-interval-containment"), question: z.string(), answerOptions: z.array(z.enum(intervalAnswers)).length(4), expectedAnswer: z.enum(intervalAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ targetLane: z.number().int().min(0).max(3), intervals: z.array(intervalSchema).length(4), videoDurationMs: z.literal(12800), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) }); export type IntervalCandidate = z.infer<typeof intervalCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => ((state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000); } function shuffled<T>(values: readonly T[], random: () => number) { const out = [...values]; for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [out[i], out[j]] = [out[j]!, out[i]!]; } return out; }
export function containmentCounts(intervals: readonly (readonly [number, number])[]) { return intervals.map(([start, end], i) => intervals.filter(([otherStart, otherEnd], j) => i !== j && start < otherStart && end > otherEnd).length); }
function makeIntervals(seed: number, targetLane: number) { const random = rng(seed), jitter = Math.floor(random() * 2), base: [number, number][] = [[2, 17], [4 + jitter, 7 + jitter], [10 - jitter, 14 - jitter], [0, 6]], order = [1, 2, 3], lanes: [number, number][] = Array(4); lanes[targetLane] = base[0]!; let k = 0; for (let lane = 0; lane < 4; lane++) if (lane !== targetLane) lanes[lane] = base[order[k++]!]!; return lanes; }
export function createIntervalCandidate(input: { split: "discovery" | "confirmatory"; seed: number; targetLane: number; visualVariant?: number }) { const intervals = makeIntervals(input.seed + 61, input.targetLane), counts = containmentCounts(intervals), visualVariant = input.visualVariant ?? input.seed % 233; if (counts[input.targetLane] !== 2 || counts.filter(v => v === 2).length !== 1) throw new Error("Interval binding failed"); return intervalCandidateSchema.parse({ id: `ic-${sha256(JSON.stringify({ ...input, intervals, visualVariant })).slice(0, 16)}`, cellId: "cell-four-intervals-eighteen-beats", split: input.split, seed: input.seed, failureModeId: "temporal-interval-containment", question: "Which lane's complete ON interval strictly contains the complete ON intervals of exactly TWO other lanes?", answerOptions: shuffled(intervalAnswers, rng(input.seed + 47)), expectedAnswer: intervalAnswers[input.targetLane], humanSolvability: "unverified", parameters: { targetLane: input.targetLane, intervals, videoDurationMs: 12800, fps: 30, visualVariant } }); }
export function createIntervalGrid() { const out: IntervalCandidate[] = []; let seed = 3_800_000; for (let rep = 0; rep < 2; rep++) for (let targetLane = 0; targetLane < 4; targetLane++) out.push(createIntervalCandidate({ split: "discovery", seed: seed++, targetLane, visualVariant: rep * 4 + targetLane })); return out; }
const colors = ["#df3c30", "#2466cc", "#1d9b5f", "#9146c7"];
export function renderIntervalSvg(candidate: IntervalCandidate, timestampMs: number) { const startMs = 700, beatMs = 650, beat = Math.floor((timestampMs - startMs) / beatMs), lanes = candidate.parameters.intervals.map(([start, end], lane) => { const on = beat >= start && beat < end, y = 205 + lane * 92; return `<text x="85" y="${y + 12}" text-anchor="middle" font-family="Arial" font-size="37" font-weight="700">${intervalAnswers[lane]}</text><rect x="135" y="${y - 38}" width="470" height="76" rx="19" fill="${on ? colors[lane] : "#d4d0c7"}" stroke="#202322" stroke-width="5"/><text x="370" y="${y + 9}" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="${on ? "#fff" : "#777"}">${on ? "ON" : "OFF"}</text>`; }).join(""), status = beat < 0 ? "GET READY" : beat < 18 ? `BEAT ${beat + 1} OF 18` : "ALL INTERVALS COMPLETE"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="670"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="47" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">COMPARE COMPLETE ON INTERVALS</text><text x="360" y="82" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Each lane switches ON once and OFF once</text><text x="360" y="128" text-anchor="middle" font-family="Arial" font-size="22" font-weight="700">${status}</text>${lanes}<text x="360" y="625" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Find the one interval that strictly contains exactly two others.</text></svg>`; }
