import { z } from "zod";
import { sha256 } from "../evaluation/hash";

export const jigsawOrderVersion = "jigsaw-strip-order-v1";
export const jigsawAnswers = ["A", "B", "C", "D"] as const;
export const jigsawOrderCandidateSchema = z.object({
  id: z.string(), cellId: z.string(), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("visual-jigsaw-order-reconstruction"), question: z.string(), answerOptions: z.array(z.enum(jigsawAnswers)).length(4), expectedAnswer: z.enum(jigsawAnswers), humanSolvability: z.literal("unverified"),
  parameters: z.object({ strips: z.number().int().min(5).max(12), curves: z.number().int().min(3).max(8), correctRow: z.number().int().min(0).max(3), visualVariant: z.number().int().nonnegative() }),
});
export type JigsawOrderCandidate = z.infer<typeof jigsawOrderCandidateSchema>;
function rng(seed:number){let state=seed>>>0;return()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/0x1_0000_0000);}
function shuffle<T>(values:readonly T[],random:()=>number){const r=[...values];for(let i=r.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[r[i],r[j]]=[r[j]!,r[i]!];}return r;}
export function createJigsawOrderCandidate(input:{split:"discovery"|"confirmatory";seed:number;strips:number;curves:number;correctRow:number;visualVariant?:number}){const visualVariant=input.visualVariant??input.seed%137;return jigsawOrderCandidateSchema.parse({id:`jo-${sha256(JSON.stringify({...input,visualVariant})).slice(0,16)}`,cellId:`cell-${sha256(JSON.stringify({strips:input.strips,curves:input.curves})).slice(0,16)}`,split:input.split,seed:input.seed,failureModeId:"visual-jigsaw-order-reconstruction",question:"Which row arranges the strips so every colored track continues smoothly across all boundaries?",answerOptions:shuffle(jigsawAnswers,rng(input.seed+3)),expectedAnswer:jigsawAnswers[input.correctRow],humanSolvability:"unverified",parameters:{...input,visualVariant}});}
export function createJigsawOrderDiscoveryGrid(){const result:JigsawOrderCandidate[]=[];let seed=2_000_000;for(let replicate=0;replicate<2;replicate++)for(let correctRow=0;correctRow<4;correctRow++)result.push(createJigsawOrderCandidate({split:"discovery",seed:seed++,strips:8,curves:5,correctRow,visualVariant:replicate*4+correctRow}));return result;}
export function jigsawRowOrders(candidate:JigsawOrderCandidate){const {strips,correctRow}=candidate.parameters;const identity=Array.from({length:strips},(_,i)=>i);const random=rng(candidate.seed+candidate.parameters.visualVariant*4099);const rows:number[][]=[];for(let row=0;row<4;row++){if(row===correctRow){rows.push(identity);continue;}let order=shuffle(identity,random);while(order.every((value,index)=>value===index)||order.some((value,index)=>index<strips-1&&value+1===order[index+1]))order=shuffle(identity,random);rows.push(order);}return rows;}
function curveY(candidate:JigsawOrderCandidate,curve:number,x:number){const r=rng(candidate.seed+curve*7919+candidate.parameters.visualVariant*17);const phase=r()*Math.PI*2;const frequency=0.7+r()*1.2;const phase2=r()*Math.PI*2;return .18+curve*(.64/Math.max(1,candidate.parameters.curves-1))+.055*Math.sin(x*Math.PI*2*frequency+phase)+.025*Math.sin(x*Math.PI*5+phase2);}
const colors=["#df3c30","#2466cc","#1b9363","#8b45c6","#e69a16","#1c8a99","#d34c98","#52622f"];
export function renderJigsawOrderSvg(candidate:JigsawOrderCandidate,oracle=false){const rows=jigsawRowOrders(candidate);const left=130,top=145,width=1600,rowHeight=190,pieceWidth=width/candidate.parameters.strips;const rendered=rows.map((order,row)=>{const pieces=order.map((source,slot)=>{const x0=left+slot*pieceWidth,y0=top+row*rowHeight;const curves=Array.from({length:candidate.parameters.curves},(_,curve)=>{const points=Array.from({length:25},(_,p)=>{const local=p/24;const sourceX=(source+local)/candidate.parameters.strips;return `${(x0+local*pieceWidth).toFixed(1)},${(y0+curveY(candidate,curve,sourceX)*145).toFixed(1)}`;}).join(" ");return `<polyline points="${points}" fill="none" stroke="${colors[curve]}" stroke-width="6" stroke-linecap="round"/>`;}).join("");return `<rect x="${x0}" y="${y0}" width="${pieceWidth}" height="145" fill="#fffef9" stroke="#202322" stroke-width="2"/>${curves}`;}).join("");const highlight=oracle&&row===candidate.parameters.correctRow?`<rect x="${left-8}" y="${top+row*rowHeight-8}" width="${width+16}" height="161" fill="none" stroke="#e23e31" stroke-width="7"/>`:"";return `<text x="70" y="${top+row*rowHeight+88}" text-anchor="middle" font-family="Arial" font-size="34" font-weight="700">${jigsawAnswers[row]}</text>${pieces}${highlight}`;}).join("");return `<svg xmlns="http://www.w3.org/2000/svg" width="1800" height="950"><rect width="100%" height="100%" fill="#f4f1e8"/><text x="55" y="60" font-family="Arial" font-size="33" font-weight="700">WHICH ROW REASSEMBLES EVERY COLORED TRACK?</text><text x="55" y="100" font-family="Arial" font-size="21" fill="#59605d">In the correct row, all five paths meet smoothly at every strip boundary.</text>${rendered}</svg>`;}
