import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const motVersion="multiple-object-tracking-v1";export const motAnswers=["A","B","C","D"]as const;
export const motCandidateSchema=z.object({id:z.string(),cellId:z.string(),split:z.enum(["discovery","confirmatory"]),seed:z.number().int().nonnegative(),failureModeId:z.literal("multiple-object-identity-tracking"),question:z.string(),answerOptions:z.array(z.enum(motAnswers)).length(4),expectedAnswer:z.enum(motAnswers),humanSolvability:z.literal("unverified"),parameters:z.object({targetEnd:z.number().int().min(0).max(3),objects:z.literal(4),videoDurationMs:z.literal(10000),fps:z.literal(30),visualVariant:z.number().int().nonnegative()})});export type MotCandidate=z.infer<typeof motCandidateSchema>;
function rng(seed:number){let s=seed>>>0;return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/0x1_0000_0000);}function shuffle<T>(v:readonly T[],r:()=>number){const a=[...v];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j]!,a[i]!];}return a;}
export function createMotCandidate(input:{split:"discovery"|"confirmatory";seed:number;targetEnd:number;visualVariant?:number}){const visualVariant=input.visualVariant??input.seed%149;return motCandidateSchema.parse({id:`mot-${sha256(JSON.stringify({...input,visualVariant})).slice(0,16)}`,cellId:"cell-four-object-crossing-tracks",split:input.split,seed:input.seed,failureModeId:"multiple-object-identity-tracking",question:"At the end, which labeled quadrant contains the disk that had the RED RING at the beginning?",answerOptions:shuffle(motAnswers,rng(input.seed+31)),expectedAnswer:motAnswers[input.targetEnd],humanSolvability:"unverified",parameters:{targetEnd:input.targetEnd,objects:4,videoDurationMs:10000,fps:30,visualVariant}});}
export function createMotDiscoveryGrid(){const r:MotCandidate[]=[];let seed=2_200_000;for(let rep=0;rep<2;rep++)for(let targetEnd=0;targetEnd<4;targetEnd++)r.push(createMotCandidate({split:"discovery",seed:seed++,targetEnd,visualVariant:rep*4+targetEnd}));return r;}
const points:[[number,number],[number,number],[number,number],[number,number]]=[[150,190],[570,190],[150,490],[570,490]];
export function motEndpointAssignment(candidate:MotCandidate){const random=rng(candidate.seed+candidate.parameters.visualVariant*2039);const remaining=shuffle([0,1,2,3].filter(x=>x!==candidate.parameters.targetEnd),random);return[candidate.parameters.targetEnd,...remaining];}
export function motPosition(candidate:MotCandidate,object:number,timestampMs:number){const assignment=motEndpointAssignment(candidate);const start=points[object]!,end=points[assignment[object]!]!;const t=Math.max(0,Math.min(1,(timestampMs-1200)/7000));const smooth=t*t*(3-2*t);const phase=(object*1.7+candidate.parameters.visualVariant*.23);const curve=Math.sin(Math.PI*t)*(object%2?1:-1)*(95+object*14);const x=start[0]+(end[0]-start[0])*smooth+Math.sin(t*Math.PI*2+phase)*42*Math.sin(Math.PI*t);const y=start[1]+(end[1]-start[1])*smooth+curve;return[x,y]as const;}
export function renderMotSvg(candidate:MotCandidate,timestampMs:number){const labels=points.map(([x,y],i)=>`<rect x="${x-92}" y="${y-92}" width="184" height="184" rx="18" fill="none" stroke="#c1c7c3" stroke-width="3" stroke-dasharray="9 9"/><text x="${x-72}" y="${y-60}" font-family="Arial" font-size="27" font-weight="700" fill="#e23e31">${motAnswers[i]}</text>`).join("");const disks=Array.from({length:4},(_,object)=>{const[x,y]=motPosition(candidate,object,timestampMs);const ring=object===0&&timestampMs>=250&&timestampMs<1200;return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="31" fill="#515855" stroke="#fff" stroke-width="3"/>${ring?`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="43" fill="none" stroke="#e23e31" stroke-width="8"/>`:""}`;}).join("");const status=timestampMs<1200?"LOCK ONTO THE RED-RINGED DISK":timestampMs<8200?"KEEP TRACKING — THE RING IS GONE":"FINAL POSITION";return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="680"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="52" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">TRACK ONE DISK THROUGH THE CROWD</text><text x="360" y="91" text-anchor="middle" font-family="Arial" font-size="20" fill="#59605d">${status}</text>${labels}${disks}</svg>`;}
