import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const parityMatrixVersion = "two-dimensional-parity-matrix-v1"; export const parityAnswers = ["A", "B", "C", "D"] as const;
export const parityCandidateSchema = z.object({ id: z.string(), cellId: z.string(), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("global-visual-parity-verification"), question: z.string(), answerOptions: z.array(z.enum(parityAnswers)).length(4), expectedAnswer: z.enum(parityAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ correctPanel: z.number().int().min(0).max(3), gridSize: z.literal(16), visualVariant: z.number().int().nonnegative() }) }); export type ParityCandidate = z.infer<typeof parityCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => ((state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000); } function shuffled<T>(values: readonly T[], random: () => number) { const out = [...values]; for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [out[i], out[j]] = [out[j]!, out[i]!]; } return out; }
function validMatrix(seed: number) { const random = rng(seed), n = 16, matrix = Array.from({ length: n }, () => Array(n).fill(false) as boolean[]); for (let y = 0; y < n - 1; y++) for (let x = 0; x < n - 1; x++) matrix[y]![x] = random() < .5; for (let y = 0; y < n - 1; y++) matrix[y]![n - 1] = matrix[y]!.slice(0, n - 1).filter(Boolean).length % 2 === 1; for (let x = 0; x < n - 1; x++) matrix[n - 1]![x] = matrix.slice(0, n - 1).filter(row => row[x]).length % 2 === 1; matrix[n - 1]![n - 1] = matrix[n - 1]!.slice(0, n - 1).filter(Boolean).length % 2 === 1; return matrix; }
export function parityMatrices(candidate: ParityCandidate) { return Array.from({ length: 4 }, (_, panel) => { const matrix = validMatrix(candidate.seed + panel * 997 + candidate.parameters.visualVariant * 43); if (panel !== candidate.parameters.correctPanel) { const random = rng(candidate.seed + panel * 7919), x = 1 + Math.floor(random() * 14), y = 1 + Math.floor(random() * 14); matrix[y]![x] = !matrix[y]![x]; } return matrix; }); }
export function parityViolations(matrix: readonly (readonly boolean[])[]) { const n = matrix.length, oddRows = matrix.map(row => row.filter(Boolean).length % 2).filter(Boolean).length, oddColumns = Array.from({ length: n }, (_, x) => matrix.filter(row => row[x]).length % 2).filter(Boolean).length; return { oddRows, oddColumns }; }
export function createParityCandidate(input: { split: "discovery" | "confirmatory"; seed: number; correctPanel: number; visualVariant?: number }) { const visualVariant = input.visualVariant ?? input.seed % 257; return parityCandidateSchema.parse({ id: `pm-${sha256(JSON.stringify({ ...input, visualVariant })).slice(0, 16)}`, cellId: "cell-four-16x16-two-dimensional-parity", split: input.split, seed: input.seed, failureModeId: "global-visual-parity-verification", question: "Which panel has an EVEN number of black cells in EVERY row AND EVERY column? Each other panel violates the rule in one row-column crossing.", answerOptions: shuffled(parityAnswers, rng(input.seed + 61)), expectedAnswer: parityAnswers[input.correctPanel], humanSolvability: "unverified", parameters: { correctPanel: input.correctPanel, gridSize: 16, visualVariant } }); }
export function createParityGrid() { const out: ParityCandidate[] = []; let seed = 4_200_000; for (let rep = 0; rep < 2; rep++) for (let correctPanel = 0; correctPanel < 4; correctPanel++) out.push(createParityCandidate({ split: "discovery", seed: seed++, correctPanel, visualVariant: rep * 4 + correctPanel })); return out; }
function matrixSvg(matrix: readonly (readonly boolean[])[], x: number, y: number, label: string) { const cell = 18, dots = matrix.flatMap((row, yy) => row.map((value, xx) => value ? `<circle cx="${x + (xx + .5) * cell}" cy="${y + (yy + .5) * cell}" r="5.2" fill="#202322"/>` : "")).join(""); return `<text x="${x + 144}" y="${y - 17}" text-anchor="middle" font-family="Arial" font-size="30" font-weight="700">${label}</text><rect x="${x}" y="${y}" width="288" height="288" fill="#fffef9" stroke="#202322" stroke-width="4"/>${Array.from({ length: 15 }, (_, i) => `<line x1="${x + (i + 1) * cell}" y1="${y}" x2="${x + (i + 1) * cell}" y2="${y + 288}" stroke="#ddd8ce"/><line x1="${x}" y1="${y + (i + 1) * cell}" x2="${x + 288}" y2="${y + (i + 1) * cell}" stroke="#ddd8ce"/>`).join("")}${dots}`; }
export function renderParitySvg(candidate: ParityCandidate, oracle = false) { const matrices = parityMatrices(candidate), positions = [[90, 170], [492, 170], [90, 525], [492, 525]] as const, panels = matrices.map((matrix, i) => `${oracle && i === candidate.parameters.correctPanel ? `<rect x="${positions[i]![0] - 12}" y="${positions[i]![1] - 48}" width="312" height="348" rx="12" fill="none" stroke="#1d9b5f" stroke-width="9"/>` : ""}${matrixSvg(matrix, positions[i]![0], positions[i]![1], parityAnswers[i]!)}`).join(""); return `<svg xmlns="http://www.w3.org/2000/svg" width="870" height="860"><rect width="100%" height="100%" fill="#eeeae0"/><text x="435" y="48" text-anchor="middle" font-family="Arial" font-size="29" font-weight="700">FIND THE 2D EVEN-PARITY MATRIX</text><text x="435" y="84" text-anchor="middle" font-family="Arial" font-size="18" fill="#59605d">Every row and every column must contain an even number of dots</text>${panels}</svg>`; }
