import { z } from "zod";
import { sha256 } from "../evaluation/hash";

export const hardSignedAccumulatorVersion = "signed-temporal-accumulator-v2";
export const hardSignedAccumulatorAnswers = ["-9", "-3", "+3", "+9"] as const;
const eventsSchema = z.array(z.number().int().min(-1).max(1)).length(61);
export const hardSignedAccumulatorCandidateSchema = z.object({ id: z.string(), cellId: z.literal("cell-sixty-one-event-signed-balance"), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("signed-temporal-state-accumulation"), question: z.string(), answerOptions: z.array(z.enum(hardSignedAccumulatorAnswers)).length(4), expectedAnswer: z.enum(hardSignedAccumulatorAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ finalBalance: z.number().int(), events: eventsSchema, videoDurationMs: z.literal(17_000), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) });
export type HardSignedAccumulatorCandidate = z.infer<typeof hardSignedAccumulatorCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; }
function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function hardSignedAccumulatorTotal(events: readonly number[]) { return events.reduce((sum, event) => sum + event, 0); }
function makeEvents(seed: number, target: number) { const positive = (61 + target) / 2, random = rng(seed), events = [...Array.from({ length: positive }, () => 1), ...Array.from({ length: 61 - positive }, () => -1)]; for (let i = events.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [events[i], events[j]] = [events[j]!, events[i]!]; } return events; }
export function createHardSignedAccumulatorCandidate(input: { seed: number; finalBalance: number; visualVariant: number; split?: "discovery" | "confirmatory" }) { const events = makeEvents(input.seed + 73, input.finalBalance); return hardSignedAccumulatorCandidateSchema.parse({ id: `sta2-${sha256(JSON.stringify({ ...input, events })).slice(0, 16)}`, cellId: "cell-sixty-one-event-signed-balance", split: input.split ?? "discovery", seed: input.seed, failureModeId: "signed-temporal-state-accumulation", question: "Starting from ZERO, where does the hidden counter end after every +1 and -1 event?", answerOptions: shuffled(hardSignedAccumulatorAnswers, rng(input.seed + 31)), expectedAnswer: input.finalBalance > 0 ? `+${input.finalBalance}` : String(input.finalBalance), humanSolvability: "unverified", parameters: { finalBalance: input.finalBalance, events, videoDurationMs: 17_000, fps: 30, visualVariant: input.visualVariant } }); }
const targets = [-9, -3, 3, 9] as const;
function grid(seedStart: number, replicates: number, split: "discovery" | "confirmatory", variantStart: number) { const output: HardSignedAccumulatorCandidate[] = []; let seed = seedStart; for (let replicate = 0; replicate < replicates; replicate += 1) for (const [index, target] of targets.entries()) output.push(createHardSignedAccumulatorCandidate({ seed: seed++, finalBalance: target, visualVariant: variantStart + replicate * 4 + index, split })); return output; }
export function createHardSignedAccumulatorGrid() { return grid(5_620_000, 2, "discovery", 0); }
export function createHardSignedAccumulatorHoldout() { return grid(5_630_000, 4, "confirmatory", 100); }
export function renderHardSignedAccumulatorSvg(candidate: HardSignedAccumulatorCandidate, timestampMs: number, control = false) { const start = 800, eventMs = 240, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 61 && local < 195 ? candidate.parameters.events[index] : 0, observed = candidate.parameters.events.slice(0, Math.max(0, Math.min(61, index + 1))), total = hardSignedAccumulatorTotal(observed), status = index < 0 ? "START AT 0" : index < 61 ? `EVENT ${index + 1} OF 61` : "SEQUENCE COMPLETE", mark = active === 1 ? `<text x="360" y="430" text-anchor="middle" font-family="Arial" font-size="230" font-weight="800" fill="#1d9b5f">+1</text>` : active === -1 ? `<text x="360" y="430" text-anchor="middle" font-family="Arial" font-size="230" font-weight="800" fill="#df3c30">−1</text>` : "", footer = control ? `CONTROL — RUNNING TOTAL: ${total >= 0 ? "+" : ""}${total}` : "Update one hidden counter after every event"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="44" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">TRACK THE HIDDEN COUNTER</text><text x="360" y="82" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Start at zero · green adds one · red subtracts one</text><text x="360" y="132" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${mark}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="18" font-weight="${control ? 700 : 400}" fill="${control ? "#147a4b" : "#59605d"}">${footer}</text></svg>`; }
