import { z } from "zod";
import { sha256 } from "../evaluation/hash";

export const temporalStackVersion = "temporal-visual-stack-v1";
export const temporalStackAnswers = ["BLUE", "GREEN", "RED", "PURPLE"] as const;
const eventSchema = z.object({ op: z.enum(["push", "pop"]), color: z.number().int().min(0).max(3).optional() });
export const temporalStackCandidateSchema = z.object({ id: z.string(), cellId: z.literal("cell-twenty-eight-event-visual-stack"), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("temporal-stack-state-manipulation"), question: z.string(), answerOptions: z.array(z.enum(temporalStackAnswers)).length(4), expectedAnswer: z.enum(temporalStackAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ targetColor: z.number().int().min(0).max(3), events: z.array(eventSchema).length(28), finalStack: z.array(z.number().int().min(0).max(3)).min(1).max(5), videoDurationMs: z.literal(13_500), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) });
export type TemporalStackCandidate = z.infer<typeof temporalStackCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; }
function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function executeTemporalStack(events: readonly z.infer<typeof eventSchema>[]) { const stack: number[] = []; for (const event of events) { if (event.op === "push") stack.push(event.color!); else { if (!stack.length) throw new Error("Stack underflow"); stack.pop(); } } return stack; }
function makeProgram(seed: number, targetColor: number) { for (let attempt = 0; attempt < 200_000; attempt += 1) { const random = rng(seed + attempt * 1877), stack: number[] = [], events: z.infer<typeof eventSchema>[] = []; let maximumDepth = 0, pops = 0; for (let step = 0; step < 28; step += 1) { const remaining = 28 - step, mustPush = stack.length === 0 || (remaining <= 3 && stack.length < 2), push = mustPush || (stack.length < 5 && random() < .59); if (push) { const color = Math.floor(random() * 4); stack.push(color); events.push({ op: "push", color }); maximumDepth = Math.max(maximumDepth, stack.length); } else { stack.pop(); events.push({ op: "pop" }); pops += 1; } } if (stack.length >= 2 && stack.length <= 5 && maximumDepth >= 4 && pops >= 8 && stack.at(-1) === targetColor) return { events, finalStack: [...stack] }; } throw new Error("Could not construct balanced temporal stack program"); }
export function createTemporalStackCandidate(input: { seed: number; targetColor: number; visualVariant: number; split?: "discovery" | "confirmatory" }) { const program = makeProgram(input.seed + 79, input.targetColor); return temporalStackCandidateSchema.parse({ id: `tst-${sha256(JSON.stringify({ ...input, program })).slice(0, 16)}`, cellId: "cell-twenty-eight-event-visual-stack", split: input.split ?? "discovery", seed: input.seed, failureModeId: "temporal-stack-state-manipulation", question: "After executing every PUSH and POP in order, what color is on TOP of the stack?", answerOptions: shuffled(temporalStackAnswers, rng(input.seed + 41)), expectedAnswer: temporalStackAnswers[input.targetColor], humanSolvability: "unverified", parameters: { targetColor: input.targetColor, ...program, videoDurationMs: 13_500, fps: 30, visualVariant: input.visualVariant } }); }
function grid(seedStart: number, replicates: number, split: "discovery" | "confirmatory", variantStart: number) { const output: TemporalStackCandidate[] = []; let seed = seedStart; for (let replicate = 0; replicate < replicates; replicate += 1) for (let targetColor = 0; targetColor < 4; targetColor += 1) output.push(createTemporalStackCandidate({ seed: seed++, targetColor, visualVariant: variantStart + replicate * 4 + targetColor, split })); return output; }
export function createTemporalStackGrid() { return grid(5_700_000, 2, "discovery", 0); }
export function createTemporalStackHoldout() { return grid(5_710_000, 4, "confirmatory", 100); }
const colors = ["#2466cc", "#1d9b5f", "#df3c30", "#9146c7"];
export function renderTemporalStackSvg(candidate: TemporalStackCandidate, timestampMs: number, control = false) { const start = 800, eventMs = 390, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 28 && local < 320 ? candidate.parameters.events[index] : undefined, observed = candidate.parameters.events.slice(0, Math.max(0, Math.min(28, index + 1))), stack = executeTemporalStack(observed), status = index < 0 ? "START WITH AN EMPTY STACK" : index < 28 ? `INSTRUCTION ${index + 1} OF 28` : "PROGRAM COMPLETE", operation = active?.op === "push" ? `<text x="360" y="250" text-anchor="middle" font-family="Arial" font-size="62" font-weight="800">PUSH</text><rect x="270" y="290" width="180" height="150" rx="18" fill="${colors[active.color!]}"/>` : active?.op === "pop" ? `<text x="360" y="335" text-anchor="middle" font-family="Arial" font-size="86" font-weight="800" fill="#df3c30">POP</text>` : "", stackView = control ? `<g>${stack.map((color, position) => `<rect x="555" y="${500 - position * 65}" width="105" height="55" rx="8" fill="${colors[color]}" stroke="#202322" stroke-width="3"/>`).join("")}<text x="607" y="545" text-anchor="middle" font-family="Arial" font-size="16" font-weight="700">VISIBLE STACK</text></g>` : ""; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="44" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">EXECUTE THE STACK PROGRAM</text><text x="360" y="82" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">PUSH adds on top · POP removes only the top item</text><text x="360" y="132" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${operation}${stackView}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">At the end, report the color on top</text></svg>`; }
