import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const temporalRunVersion = "temporal-run-maximum-v1"; export const temporalRunAnswers = ["3", "4", "5", "6"] as const; const sequenceSchema = z.array(z.number().int().min(0).max(1)).length(48);
export const temporalRunCandidateSchema = z.object({ id: z.string(), cellId: z.literal("cell-forty-eight-event-longest-red-run"), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("temporal-run-length-extrema"), question: z.string(), answerOptions: z.array(z.enum(temporalRunAnswers)).length(4), expectedAnswer: z.enum(temporalRunAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ maximumRun: z.number().int().min(3).max(6), sequence: sequenceSchema, videoDurationMs: z.literal(15_000), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) }); export type TemporalRunCandidate = z.infer<typeof temporalRunCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; } function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function longestTemporalRun(values: readonly number[]) { let best = 0, current = 0; for (const value of values) { current = value === 1 ? current + 1 : 0; best = Math.max(best, current); } return best; }
function makeSequence(seed: number, target: number) { const random = rng(seed), values: number[] = []; while (values.length < 48) { const current = values.slice(-target + 1).every((value) => value === 1) ? 0 : random() < .48 ? 1 : 0; values.push(current); } const start = 2 + Math.floor(random() * (44 - target)); for (let i = start - 1; i <= start + target; i += 1) values[i] = i >= start && i < start + target ? 1 : 0; if (longestTemporalRun(values) !== target) return makeSequence(seed + 104729, target); return values; }
export function createTemporalRunCandidate(input: { seed: number; maximumRun: number; visualVariant: number }) { const values = makeSequence(input.seed + 91, input.maximumRun); return temporalRunCandidateSchema.parse({ id: `trm-${sha256(JSON.stringify({ ...input, values })).slice(0, 16)}`, cellId: "cell-forty-eight-event-longest-red-run", split: "discovery", seed: input.seed, failureModeId: "temporal-run-length-extrema", question: "What is the LONGEST uninterrupted run of consecutive RED SQUARES in the complete sequence?", answerOptions: shuffled(temporalRunAnswers, rng(input.seed + 37)), expectedAnswer: String(input.maximumRun), humanSolvability: "unverified", parameters: { maximumRun: input.maximumRun, sequence: values, videoDurationMs: 15_000, fps: 30, visualVariant: input.visualVariant } }); }
export function createTemporalRunGrid() { const output: TemporalRunCandidate[] = []; let seed = 5_500_000; for (let replicate = 0; replicate < 2; replicate += 1) for (let target = 3; target <= 6; target += 1) output.push(createTemporalRunCandidate({ seed: seed++, maximumRun: target, visualVariant: replicate * 4 + target - 3 })); return output; }
export function createTemporalRunHoldout() { const output: TemporalRunCandidate[] = []; let seed = 5_510_000; for (let replicate = 0; replicate < 4; replicate += 1) for (let target = 3; target <= 6; target += 1) { const candidate = createTemporalRunCandidate({ seed: seed++, maximumRun: target, visualVariant: 100 + replicate * 4 + target - 3 }); output.push(temporalRunCandidateSchema.parse({ ...candidate, split: "confirmatory" })); } return output; }
function temporalRunState(values: readonly number[]) { let current = 0, best = 0; for (const value of values) { current = value === 1 ? current + 1 : 0; best = Math.max(best, current); } return { current, best }; }
export function renderTemporalRunSvg(candidate: TemporalRunCandidate, timestampMs: number, runningMaximumControl = false) { const start = 800, eventMs = 270, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 48 && local < 220 ? candidate.parameters.sequence[index] : -1, observed = candidate.parameters.sequence.slice(0, Math.max(0, Math.min(48, index + 1))), runState = temporalRunState(observed), status = index < 0 ? "GET READY" : index < 48 ? `EVENT ${index + 1} OF 48` : "SEQUENCE COMPLETE", shape = active === 1 ? `<rect x="255" y="270" width="210" height="210" rx="18" fill="#df3c30"/>` : active === 0 ? `<circle cx="360" cy="375" r="105" fill="#2466cc"/>` : "", footer = runningMaximumControl ? `CONTROL — CURRENT: ${runState.current} · LONGEST SO FAR: ${runState.best}` : "Remember only the largest number of consecutive red squares"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="44" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">FIND THE LONGEST RED RUN</text><text x="360" y="82" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">A blue circle breaks the run immediately</text><text x="360" y="132" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${shape}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="17" font-weight="${runningMaximumControl ? 700 : 400}" fill="${runningMaximumControl ? "#147a4b" : "#59605d"}">${footer}</text></svg>`; }
