import { z } from "zod";
import { sha256 } from "../evaluation/hash";

export const hardTemporalRunVersion = "temporal-run-maximum-v2";
export const hardTemporalRunAnswers = ["4", "5", "6", "7"] as const;
const sequenceSchema = z.array(z.number().int().min(0).max(1)).length(80);
export const hardTemporalRunCandidateSchema = z.object({
  id: z.string(), cellId: z.literal("cell-eighty-event-longest-red-run"), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("temporal-run-length-extrema"), question: z.string(), answerOptions: z.array(z.enum(hardTemporalRunAnswers)).length(4), expectedAnswer: z.enum(hardTemporalRunAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ maximumRun: z.number().int().min(4).max(7), sequence: sequenceSchema, videoDurationMs: z.literal(15_000), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }),
});
export type HardTemporalRunCandidate = z.infer<typeof hardTemporalRunCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; }
function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function longestHardTemporalRun(values: readonly number[]) { let best = 0, current = 0; for (const value of values) { current = value === 1 ? current + 1 : 0; best = Math.max(best, current); } return best; }
function makeSequence(seed: number, target: number) { const random = rng(seed), values: number[] = []; while (values.length < 80) { const current = values.slice(-target + 1).every((value) => value === 1) ? 0 : random() < .49 ? 1 : 0; values.push(current); } const start = 4 + Math.floor(random() * (72 - target)); for (let i = start - 1; i <= start + target; i += 1) values[i] = i >= start && i < start + target ? 1 : 0; if (longestHardTemporalRun(values) !== target) return makeSequence(seed + 104729, target); return values; }
export function createHardTemporalRunCandidate(input: { seed: number; maximumRun: number; visualVariant: number; split?: "discovery" | "confirmatory" }) { const values = makeSequence(input.seed + 91, input.maximumRun); return hardTemporalRunCandidateSchema.parse({ id: `trm2-${sha256(JSON.stringify({ ...input, values })).slice(0, 16)}`, cellId: "cell-eighty-event-longest-red-run", split: input.split ?? "discovery", seed: input.seed, failureModeId: "temporal-run-length-extrema", question: "What is the LONGEST uninterrupted run of consecutive RED SQUARES in the complete sequence?", answerOptions: shuffled(hardTemporalRunAnswers, rng(input.seed + 37)), expectedAnswer: String(input.maximumRun), humanSolvability: "unverified", parameters: { maximumRun: input.maximumRun, sequence: values, videoDurationMs: 15_000, fps: 30, visualVariant: input.visualVariant } }); }
function createGrid(seedStart: number, replicates: number, split: "discovery" | "confirmatory", variantStart: number) { const output: HardTemporalRunCandidate[] = []; let seed = seedStart; for (let replicate = 0; replicate < replicates; replicate += 1) for (let target = 4; target <= 7; target += 1) output.push(createHardTemporalRunCandidate({ seed: seed++, maximumRun: target, visualVariant: variantStart + replicate * 4 + target - 4, split })); return output; }
export function createHardTemporalRunGrid() { return createGrid(5_520_000, 2, "discovery", 0); }
export function createHardTemporalRunHoldout() { return createGrid(5_530_000, 4, "confirmatory", 100); }
function runState(values: readonly number[]) { let current = 0, best = 0; for (const value of values) { current = value === 1 ? current + 1 : 0; best = Math.max(best, current); } return { current, best }; }
export function renderHardTemporalRunSvg(candidate: HardTemporalRunCandidate, timestampMs: number, control = false) { const start = 700, eventMs = 165, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 80 && local < 135 ? candidate.parameters.sequence[index] : -1, observed = candidate.parameters.sequence.slice(0, Math.max(0, Math.min(80, index + 1))), state = runState(observed), status = index < 0 ? "GET READY" : index < 80 ? `EVENT ${index + 1} OF 80` : "SEQUENCE COMPLETE", shape = active === 1 ? `<rect x="255" y="270" width="210" height="210" rx="18" fill="#df3c30"/>` : active === 0 ? `<circle cx="360" cy="375" r="105" fill="#2466cc"/>` : "", footer = control ? `CONTROL — CURRENT: ${state.current} · LONGEST SO FAR: ${state.best}` : "A blue circle resets the current red run to zero"; return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="44" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">FIND THE LONGEST RED RUN</text><text x="360" y="82" text-anchor="middle" font-family="Arial" font-size="17" fill="#59605d">Retain only the largest uninterrupted run</text><text x="360" y="132" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${shape}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="17" font-weight="${control ? 700 : 400}" fill="${control ? "#147a4b" : "#59605d"}">${footer}</text></svg>`; }
