import { z } from "zod"; import { sha256 } from "../evaluation/hash";
export const transitionCountVersion = "temporal-transition-count-v1"; export const transitionCountAnswers = ["3", "4", "5", "6"] as const; const sequence = z.array(z.number().int().min(0).max(3)).length(32);
export const transitionCountCandidateSchema = z.object({ id: z.string(), cellId: z.literal("cell-thirty-two-symbol-target-transition-count"), split: z.enum(["discovery", "confirmatory"]), seed: z.number().int().nonnegative(), failureModeId: z.literal("temporal-pattern-counting"), question: z.string(), answerOptions: z.array(z.enum(transitionCountAnswers)).length(4), expectedAnswer: z.enum(transitionCountAnswers), humanSolvability: z.literal("unverified"), parameters: z.object({ targetCount: z.number().int().min(3).max(6), sequence, videoDurationMs: z.literal(13_000), fps: z.literal(30), visualVariant: z.number().int().nonnegative() }) }); export type TransitionCountCandidate = z.infer<typeof transitionCountCandidateSchema>;
function rng(seed: number) { let state = seed >>> 0; return () => (state = (Math.imul(state, 1664525) + 1013904223) >>> 0) / 0x1_0000_0000; } function shuffled<T>(values: readonly T[], random: () => number) { const output = [...values]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [output[i], output[j]] = [output[j]!, output[i]!]; } return output; }
export function countTargetTransitions(values: readonly number[]) { let count = 0; for (let i = 1; i < values.length; i += 1) if (values[i - 1] === 0 && values[i] === 2) count += 1; return count; }
function makeSequence(seed: number, target: number) { for (let attempt = 0; attempt < 100_000; attempt += 1) { const random = rng(seed + attempt * 1543), output = Array.from({ length: 32 }, () => Math.floor(random() * 4)); if (countTargetTransitions(output) === target) return output; } throw new Error("Could not construct transition sequence"); }
export function createTransitionCountCandidate(input: { seed: number; targetCount: number; visualVariant: number }) { const values = makeSequence(input.seed + 79, input.targetCount); return transitionCountCandidateSchema.parse({ id: `tc-${sha256(JSON.stringify({ ...input, values })).slice(0, 16)}`, cellId: "cell-thirty-two-symbol-target-transition-count", split: "discovery", seed: input.seed, failureModeId: "temporal-pattern-counting", question: "How many times is a BLUE CIRCLE immediately followed by a RED SQUARE in the complete sequence? Count overlapping occurrences.", answerOptions: shuffled(transitionCountAnswers, rng(input.seed + 31)), expectedAnswer: String(input.targetCount), humanSolvability: "unverified", parameters: { targetCount: input.targetCount, sequence: values, videoDurationMs: 13_000, fps: 30, visualVariant: input.visualVariant } }); }
export function createTransitionCountGrid() { const output: TransitionCountCandidate[] = []; let seed = 5_100_000; for (let replicate = 0; replicate < 2; replicate += 1) for (let count = 3; count <= 6; count += 1) output.push(createTransitionCountCandidate({ seed: seed++, targetCount: count, visualVariant: replicate * 4 + count - 3 })); return output; }
export function createTransitionCountHoldout() { const output: TransitionCountCandidate[] = []; let seed = 5_110_000; for (let replicate = 0; replicate < 4; replicate += 1) for (let count = 3; count <= 6; count += 1) { const candidate = createTransitionCountCandidate({ seed: seed++, targetCount: count, visualVariant: 100 + replicate * 4 + count - 3 }); output.push(transitionCountCandidateSchema.parse({ ...candidate, split: "confirmatory" })); } return output; }
const colors = ["#2466cc", "#f4d934", "#df3c30", "#9146c7"];
function symbolSvg(symbol: number, x: number, y: number, size: number) { if (symbol === 0) return `<circle cx="${x}" cy="${y}" r="${size * .44}" fill="${colors[symbol]}"/>`; if (symbol === 1) return `<polygon points="${x},${y - size * .5} ${x - size * .48},${y + size * .42} ${x + size * .48},${y + size * .42}" fill="${colors[symbol]}"/>`; if (symbol === 2) return `<rect x="${x - size * .42}" y="${y - size * .42}" width="${size * .84}" height="${size * .84}" rx="${size * .08}" fill="${colors[symbol]}"/>`; return `<path d="M${x - size * .48} ${y}H${x + size * .48}M${x} ${y - size * .48}V${y + size * .48}" stroke="${colors[symbol]}" stroke-width="${size * .28}"/>`; }
export function renderTransitionCountSvg(candidate: TransitionCountCandidate, timestampMs: number, counterControl = false) { const start = 900, eventMs = 320, index = Math.floor((timestampMs - start) / eventMs), local = timestampMs - start - index * eventMs, active = index >= 0 && index < 32 && local < 250 ? candidate.parameters.sequence[index] : -1, status = index < 0 ? "GET READY" : index < 32 ? `SYMBOL ${index + 1} OF 32` : "SEQUENCE COMPLETE", observed = candidate.parameters.sequence.slice(0, Math.max(0, Math.min(32, index + 1))), count = countTargetTransitions(observed); return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="640"><rect width="100%" height="100%" fill="#eeeae0"/><text x="360" y="45" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700">COUNT ONE SPECIFIC TRANSITION</text><text x="360" y="82" text-anchor="middle" font-family="Arial" font-size="18">Count every</text>${symbolSvg(0, 300, 125, 44)}<text x="360" y="134" text-anchor="middle" font-family="Arial" font-size="28">→</text>${symbolSvg(2, 420, 125, 44)}<text x="360" y="185" text-anchor="middle" font-family="Arial" font-size="21" font-weight="700">${status}</text>${active >= 0 ? symbolSvg(active, 360, 385, 190) : ""}<text x="360" y="590" text-anchor="middle" font-family="Arial" font-size="18" font-weight="${counterControl ? 700 : 400}" fill="${counterControl ? "#147a4b" : "#59605d"}">${counterControl ? `CONTROL — TARGET TRANSITIONS SO FAR: ${count}` : "Only adjacent BLUE CIRCLE → RED SQUARE pairs count"}</text></svg>`; }
