import Image from "next/image";
import { Download } from "lucide-react";

const images = [
  ["small-object.svg", "Small-object scale specimen"],
  ["patch-phase.svg", "Patch-phase geometry specimen"],
  ["attribute-binding.svg", "Attribute-binding specimen"],
  ["numerosity-density.svg", "Numerosity-density specimen"],
] as const;
const videos = [
  ["brief-event.mp4", "Brief purple event specimen"],
  ["event-order.mp4", "Sequential event-order specimen"],
  ["identity-occlusion.mp4", "Identity-through-occlusion specimen"],
  ["event-counting.mp4", "Repeated-event count specimen"],
] as const;

export function ReferenceArtifacts() {
  return (
    <section className="reference-artifacts">
      <div className="section-heading split-heading">
        <div>
          <p className="eyebrow">Reference artifacts</p>
          <h2>
            Files, not just
            <br />
            browser effects.
          </h2>
        </div>
        <p>
          These deterministic assets are generated by the repository build script for evaluation-pipeline
          development. They are public demonstrations, not scored seeds.
        </p>
      </div>
      <div className="artifact-grid">
        {images.map(([file, alt]) => (
          <figure key={file}>
            <Image src={`/generated/${file}`} width={640} height={400} alt={alt} />
            <figcaption>
              <span>{alt}</span>
              <a href={`/generated/${file}`} download>
                <Download size={14} /> SVG
              </a>
            </figcaption>
          </figure>
        ))}
        {videos.map(([file, alt]) => (
          <figure key={file}>
            <video
              src={`/generated/${file}`}
              aria-label={alt}
              controls
              muted
              loop
              playsInline
              preload="metadata"
            />
            <figcaption>
              <span>{alt}</span>
              <a href={`/generated/${file}`} download>
                <Download size={14} /> MP4
              </a>
            </figcaption>
          </figure>
        ))}
      </div>
    </section>
  );
}
