import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { z } from "zod";
import { createWireTracingHoldout, wireTracingCandidateSchema, wireTracingGeneratorVersion } from "../src/lib/discovery/wire-tracing";
import { sha256 } from "../src/lib/evaluation/hash";
const discoveryPath = resolve("evaluation/discovery/wire-tracing-discovery-v1.json");
const rankingPath = resolve("evaluation/discovery/wire-tracing-ranking-v1.json");
const outputPath = resolve("evaluation/discovery/wire-tracing-confirmatory-v1.json");
const discoveryBytes = await readFile(discoveryPath); const rankingBytes = await readFile(rankingPath);
const discovery = z.object({ candidates: z.array(wireTracingCandidateSchema) }).parse(JSON.parse(discoveryBytes.toString()));
const ranking = z.object({ planSha256: z.string(), cells: z.array(z.object({ cellId: z.string(), observedAdmitted: z.boolean(), evidenceComplete: z.boolean() })) }).parse(JSON.parse(rankingBytes.toString()));
if (ranking.planSha256 !== sha256(discoveryBytes)) throw new Error("Stale ranking.");
const winner = ranking.cells.find((cell) => cell.observedAdmitted && cell.evidenceComplete);
if (!winner) throw new Error("No all-model below-50% cell.");
const representative = discovery.candidates.find((candidate) => candidate.cellId === winner.cellId)!;
const candidates = createWireTracingHoldout(representative);
const body = `${JSON.stringify({ id: "wire-tracing-confirmatory-v1", createdAt: "2026-09-01", generatorVersion: wireTracingGeneratorVersion, status: "frozen-confirmatory-holdout", derivedFrom: { discoveryPlanSha256: sha256(discoveryBytes), rankingSha256: sha256(rankingBytes), selectedCellId: winner.cellId }, holdoutGuarantees: { balancedEndpoints: true, candidatesPerModel: 16, newSeedsPathsSourcesAndVisualVariants: true, humanSolvability: "unverified-until-blinded-human-baseline" }, interventions: [{ id: "native-image", description: "Unmodified wire diagram; primary condition." }, { id: "oracle-highlighted-path", description: "Target wire highlighted red; positive control." }], candidates }, null, 2)}\n`;
await mkdir(dirname(outputPath), { recursive: true }); await writeFile(outputPath, body);
console.log(JSON.stringify({ outputPath, sha256: sha256(body), selectedCellId: winner.cellId, candidates: candidates.length }, null, 2));
