import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { z } from "zod";
import { frontierAdmissionPolicy, scoreCrossModelCells } from "../src/lib/discovery/admission";
import { wireTracingCandidateSchema } from "../src/lib/discovery/wire-tracing";
import { sha256 } from "../src/lib/evaluation/hash";
import { evaluationRunSchema } from "../src/lib/evaluation/schema";
const planPath = resolve("evaluation/discovery/wire-tracing-discovery-v1.json");
const protocolPath = resolve("evaluation/plans/wire-tracing-screen-v2.json");
const outputPath = resolve("evaluation/discovery/wire-tracing-ranking-v1.json");
const planBytes = await readFile(planPath);
const plan = z.object({ id: z.string(), candidates: z.array(wireTracingCandidateSchema) }).parse(JSON.parse(planBytes.toString()));
const protocol = z.object({ evaluationPlanId: z.string(), evaluationPlanSha256: z.string(), models: z.array(z.object({ modelId: z.string() })) }).parse(JSON.parse(await readFile(protocolPath, "utf8")));
if (protocol.evaluationPlanId !== plan.id || protocol.evaluationPlanSha256 !== sha256(planBytes)) throw new Error("Protocol mismatch.");
const resultPaths = ["gemini", "kimi", "qwen"].map((tag) => resolve(`evaluation/results/wire-tracing-discovery-v2-${tag}.jsonl`));
const records = (await Promise.all(resultPaths.map(async (path) => (await readFile(path, "utf8")).split("\n").filter(Boolean).map((line) => evaluationRunSchema.parse(JSON.parse(line)))))).flat();
const bySeed = new Map(plan.candidates.map((candidate) => [candidate.seed, candidate]));
const observations = records.flatMap((record) => { const candidate = bySeed.get(record.seed); return candidate ? [{ candidateId: candidate.id, modelId: record.modelId, outcome: record.emptyResponse ? "no-answer" as const : record.status === "pending-review" ? "review" as const : record.correct ? "correct" as const : "incorrect" as const, costUsd: record.costUsd }] : []; });
const policy = { ...frontierAdmissionPolicy, minimumSubstantiveAnswersPerModel: 4 };
const targetModelIds = protocol.models.map((model) => model.modelId);
const cells = scoreCrossModelCells(plan.candidates, observations, targetModelIds, policy).map((score) => ({ ...score, crossings: plan.candidates.find((candidate) => candidate.cellId === score.cellId)!.parameters.crossings }));
await writeFile(outputPath, `${JSON.stringify({ id: "wire-tracing-ranking-v1", status: "discovery-not-confirmatory", planSha256: sha256(planBytes), targetModelIds, policy, records: records.length, totalCostUsd: records.reduce((sum, record) => sum + record.costUsd, 0), selectionRule: "minimize the easiest target model solve rate with complete substantive balanced cells", cells }, null, 2)}\n`);
console.log(JSON.stringify({ outputPath, cells }, null, 2));
